### ISSUE TITLE
eldoc information

### ISSUE THREAD

**Issue by mallt** [NicolasPetton/Indium#100]
Would it be possible for Indium to provide eldoc information for function calls? F.ex. by using a function similar to the [`argumentNames()` function in Prototype](https://github.com/sstephenson/prototype/blob/master/src/prototype/lang/function.js#L38)? Thanks!

**Comment by NicolasPetton** [comment]
That's out of the scope of Indium, but I'm using Ternjs which provides very good support for type inference, and the Emacs mode has eldoc support.
