### ISSUE TITLE
Unexpected interaction between REPL and catching all exceptions

### ISSUE THREAD

**Issue by shawwn** [NicolasPetton/Indium#101]
After starting a new REPL and turning on catch all exceptions, I ran `throw new Error("foo")` in the REPL and got this:

![indium-1](https://user-images.githubusercontent.com/59632/30924036-2e246bb0-a373-11e7-82c4-acb87a11959f.png)

From the standpoint of a complete newbie (me), there are three unexpected things here:

- The stack is empty. I was hoping to see a trace showing some of the internals of whatever is evaluating the Javascript, so that I can learn more about what precisely is evaluating the REPL code.

- It seems impossible to quit the debugger (or to do anything else). Nothing happens when I press SPC, i, o, c, n, or p. Pressing `e` gives a prompt `Evaluating on frame: (nil): ` but nothing happens after typing any value.

- The REPL is frozen, making it impossible to enter new values.

The only option seems to be to terminate the node process and start a new one.

Apologies if I'm overlooking something obvious. Is there any command like `indium-debugger-quit` so that execution can resume in this situation?

"Well, don't do that!" may be an acceptable answer here. ;)

**Comment by NicolasPetton** [comment]
Regarding the stack, there's nothing to be done, as Indium displays whatever stack the runtime gives us.

Regarding the debugger and REPL being frozen, pressing `c` in the debugger works for me (it proceeds the execution, throws the exception and logs it in the REPL). I can use the REPL normally after that.

I guess I'll need more info to reproduce your issue:

- Could you paste the recent logging from the `*messages*` buffer? After pressing `c` from the debugger?
- If you set `websocket-debug` to `t` before reproducing the problem, can you paste the content of your `*websocket-ID` buffer?

Thanks!

**Comment by NicolasPetton** [comment]
@shawwn any update on this one?

**Comment by shawwn** [comment]
Yeah, it was my fault. I was using `evil-mode` (vim emulation). I had to press `i` to go into normal mode before pressing `c` or anything else.
