### ISSUE TITLE
Indium requires emacs 25

### ISSUE THREAD

**Issue by shawwn** [NicolasPetton/Indium#102]
Indium uses the `map` library, which is only available on Emacs 25+. Indium seems to only use the following functions:

```
map-apply
map-delete
map-elt
map-nested-elt
map-put
map-values
map-values-apply
```

Are there any other reasons to require Emacs 25?

From a compatibility standpoint, it might be better to copy these functions into Indium (prefixing them with `indium-`).

On the other hand, I guess it's fine to tell users to upgrade their Emacs. But in practice people are reluctant to do that.

**Comment by shawwn** [comment]
Additional dependencies:

```
pcase-defmacro
cl-defmethod
```

It looks like it would be nontrivial to add backwards compatibility, so I guess the best option would be to tell users to upgrade.

I wonder if there's a compatibility shim for Emacs 24?

I'm curious how to handle this situation in my own project. Should I just use Emacs 25 libraries, forcing users to upgrade?

Either way, I'll close this since it's not really an issue.

**Comment by NicolasPetton** [comment]
Yes, Indium requires Emacs 25, it uses several of the new libraries introduced in Emacs 25.1, and I have no plan to support older Emacsen.

Emacs 26.1 is around the corner, however I want to keep compatibility with Emacs 25.x for quite some time.
