### ISSUE TITLE
Breakpoints placed before connecting to Chrome don't work

### ISSUE THREAD

**Issue by shawwn** [NicolasPetton/Indium#107]
When source maps are in use:

If you open a file, e.g. `src/App.js`, place some breakpoints, then connect to a Chrome tab, the breakpoint location will fail because the sourcemap won't be downloaded.

(If you connect to a Chrome tab first, then place a breakpoint, the sourcemap will be downloaded and the breakpoint will work fine.)

**Comment by NicolasPetton** [comment]
Indeed, this currently only works when not using sourcemaps.
