### ISSUE TITLE
Breakpoints fail in certain webpack configurations

### ISSUE THREAD

**Issue by shawwn** [NicolasPetton/Indium#108]
If a webpack config is set to generate bundle files using template `bundle.[hash].js`, then each time the source code of the webapp is modified, a new `bundle.[hash].js` file and `bundle.[hash].js.map` sourcemap will be generated.

If you place a breakpoint in any source file, then modify and save the file, webpack will rebuild the bundle. The old breakpoint will stop working, and the new sourcemap won't be downloaded until you place a fresh breakpoint.

I think we can solve this. Idea: We could download the updated sourcemap whenever the page reloads, and then remove and reinsert all breakpoints whenever a sourcemap is downloaded. (Conceptually the same operation as going to each breakpoint and typing `C-c b k C-c b b`.)

There's probably a nicer solution, of course.

**Comment by shawwn** [comment]
I see you've already been working on this in the `breakpoint-updates` branch!

**Comment by NicolasPetton** [comment]
@shawwn have you tried it with the latest `master`? It might just work ™️

**Comment by NicolasPetton** [comment]
@shawwn up?

**Comment by NicolasPetton** [comment]
@shawwn another up :)

**Comment by NicolasPetton** [comment]
It's working nicely for me, so I'm closing this issue. If it's still a problem for you, feel free to reopen it.
