### ISSUE TITLE
When evaluating a React event / proxy object, the inspector shows no properties

### ISSUE THREAD

**Issue by shawwn** [NicolasPetton/Indium#109]
I'm not sure if this is a problem with React events specifically, or proxy objects in general.

Using the following indium settings:

```
(setq indium-nodejs-inspect-brk t)
(setq indium-debugger-inspect-when-eval t)
```

Say you create a React class called Button that binds an `onClick` callback.

If you place a breakpoint within the callback function, the first argument `evt` will be a synthetic React event object.

If you hit the breakpoint and press `l` to show locals, the inspector will show:

```
 evt: Proxy { dispatchConfig: Object, _targetInst: ReactDOMComponent, ....
```

which is expected behavior.

But if you press `e` to evaluate, and then type `evt`, the inspector will simply show:

```
Proxy
```

and won't show any other information about the object.

If you box the event by evaluating `[evt]` or `{foo: evt}`, the inspector will correctly display the properties.

**Comment by NicolasPetton** [comment]
@shawwn have you tried the same thing in Chrome?

**Comment by NicolasPetton** [comment]
I found the reason (see #115). The problem was that internal properties were never displayed in the inspector.
