### ISSUE TITLE
Code underneath symlinked directories fails to breakpoint

### ISSUE THREAD

**Issue by shawwn** [NicolasPetton/Indium#110]
When sourcemaps are being used, if a webpack configuration contains:

```js
config.output.devtoolModuleFilenameTemplate = '[absolute-resource-path]';
```

Then the sourcemap will embed absolute source file paths. However, those absolute paths will use the truename (realpath) of the file. This causes a mismatch between `buffer-file-name` and the sourcemap's source path, which causes `indium-script-generated-location-at-point` to fail.

**Comment by NicolasPetton** [comment]
Hi! 

The new version on master (which has a lot of changes, see here https://emacs.cafe/emacs/javascript/indium/2018/08/14/indium.html) should fix the issue.
