### ISSUE TITLE
Sourcemap parsing performance

### ISSUE THREAD

**Issue by shawwn** [NicolasPetton/Indium#112]
When running indium on a codebase with a 6.7MB sourcemap, it takes about 5-10 seconds from the time a breakpoint is placed until the sourcemap has been downloaded + finished parsing. Since this happens any time the user changes the source code, this is somewhat detrimental to interactive development. But I think we can optimize it.

The culprit is mostly `sourcemap.el`: ~15% of time is spent in `json-read-from-string`, and the rest is spent in `sourcemap--parse-mappings`.

It might be better to create our own version of `sourcemap.el` that lazy-loads the mappings as needed. If the user wants to place a breakpoint in `src/foo.js`, then only mappings related to `src/foo.js` need to be parsed.

**Comment by NicolasPetton** [comment]
The JSON part will be resolved soon as Emacs will move to a faster JSON library using C bindings.
I'm not sure what to do with the `sourcemap.el` part, as I have PRs opened there for quite some time without any feedback from its maintainer.

**Comment by NicolasPetton** [comment]
@shawwn Indium is now using its own sourcemap library. Is it any faster than before?

**Comment by NicolasPetton** [comment]
@shawwn I'm closing this issue as sourcemaps seem to be fast enough for me. If it's still an issue for you, please reopen this ticket.

**Comment by TatriX** [comment]
Note: looks like a good use case for something like https://github.com/ubolonton/emacs-module-rs.

**Comment by NicolasPetton** [comment]
TatriX <notifications@github.com> writes:

> Note: looks like a good use case for something like
> https://github.com/ubolonton/emacs-module-rs.

I'm thinking about using the new JSON bindings from Emacs master when
available, and fallback to json.el.
