### ISSUE TITLE
Handle data: url sourcemaps

### ISSUE THREAD

**Issue by felipeochoa** [NicolasPetton/Indium#127]
I'm using indium with jest, which transforms files on the fly and sets sourcemap urls as base64 encoded data. Here's an example: `data:application/json;charset=utf-8;base64,eyJ2...`

As you can imagine, these are extremely long "urls", which I think indium tries to resolve to a file. Emacs complains somewhere with the following error:

> **file-error** *Opening input file* File name too long /path/to/original/file's/dir/data:application/json;charset=utf-8;base64,eyJ2Z...`

`websocket-default-error-handler` displays a warning for this and then indium is left in an inconsistent state. 

I'd be happy to submit a PR for this, but I can't figure out where exactly the file is attempted to be opened. (Since the callback is asynchronous I can't just the debugger) If you give me a couple of pointers, I'll take a crack at it

**Comment by NicolasPetton** [comment]
Thanks for reporting this issue!

If you want to get a debugger, you can set `websocket-callback-debug-on-error` to `t`.
If you need more help, just tell me!

**Comment by felipeochoa** [comment]
Thanks! That was all the advice I needed. The unit-testing was a bit daunting, but hopefully it's an OK test :)
