### ISSUE TITLE
Name has trademark issues 

### ISSUE THREAD

**Issue by robbyoconnor** [NicolasPetton/Indium#13]
In case you weren't aware, there's a trademark issue here. See pugjs/pug/issues/2184 for more information...probably a wise idea to rename the project. 

TL;DR: Jade was forced to switch to Pug. You'll face the same issues.

**Comment by NicolasPetton** [comment]
> In case you weren't aware, there's a trademark issue here. See
> pugjs/pug/issues/2184 for more information...probably a wise idea to
> rename the project.

Indeed, thanks for the reminder.

Any idea?

**Comment by robbyoconnor** [comment]
AdeJ? (Awesome Development Environment for Javascript =) -- I'm not sure sadly -- I suck at naming things...but I don't want you to get the same thing...

**Comment by bleggett** [comment]
DEEJ   (Development Environment in Emacs for Javascript)
JADEN (Javascript Awesome Development ENvironment)
JUDE (Javascript Ultimate Development Environment)

Alternatively, just pick a nice/fun word and forget about the acronym :)

**Comment by line55** [comment]
Javascript Inspector and Tools for Emacs (JITE) ?

What about Let & Constly? Sounds like hip barber shop. Also bonus points for the ampersand.

**Comment by NicolasPetton** [comment]
The project is now named Indium!

**Comment by robbyoconnor** [comment]
YAY! I'm happy now!
