### ISSUE TITLE
Evil compatibility

### ISSUE THREAD

**Issue by kandros** [NicolasPetton/Indium#130]
As of now debugging commands (continue, step over, list variables ec..)  get consumed by evil mode normal state.

I'm not quite sure what is the best approach to handle these cases

**Comment by kandros** [comment]
Working solution
 
```
(evil-make-overriding-map indium-debugger-mode-map)
(evil-make-overriding-map indium-debuggerlocals-mode-map)
```

**Comment by asimpson** [comment]
I typically just revert to emacs binds in these situations like so:
`(add-to-list 'evil-emacs-state-modes 'indium-repl-mode)`

**Comment by NicolasPetton** [comment]
@asimpson thanks for providing a solution.
