### ISSUE TITLE
No URL associated with the current buffer.  Setup an Indium workspace first

### ISSUE THREAD

**Issue by kandros** [NicolasPetton/Indium#131]
For a webpack (create-react-app) project the stepping debugger works just fine if the breakpoint is set from chrome or by the debugger keyword, if i set it from within emacs using `indium-add-breakpoint` it throws

No URL associated with the current buffer.  Setup an Indium workspace first

 I tried to map the workspace to local folder in chrome and put a `.indium` file inside public folder but haven’t been able to make it work

**Comment by NicolasPetton** [comment]
@kandros can you provide a recipe to reproduce the problem starting from a brand new project made with `create-react-app`? It would be much easier for me to help and find the problem.

**Comment by NicolasPetton** [comment]
@kandros up?

**Comment by kandros** [comment]
Sorry, I have very little time at the moment, will reopen the issue with more details for repro
