### ISSUE TITLE
emacs struck on Downloading sourcemap file…done

### ISSUE THREAD

**Issue by kandros** [NicolasPetton/Indium#132]
In a quite big project (create-react-app based) when i add a breakpoint using `indium-add-breackpoint`  

i see a lot of messages `Downloading sourcemap file…done` but it never finished (waited for minutes), and emacs becomes unresponsive and I have to kill emacs process.

**Comment by NicolasPetton** [comment]
Hi @kandros!

Thanks for reporting this issue. Could you give me a link to a repository help me reproduce it?

**Comment by kandros** [comment]
Sorry, I have very little time at the moment, will reopen the issue with more details for repro
