### ISSUE TITLE
Debugging server-side node project with sourcemap

### ISSUE THREAD

**Issue by chris-kahn** [NicolasPetton/Indium#133]
I'm a bit lost on getting this working in my project. I'm using spacemacs.

I have a project with a `webpack.config.server.js` file that runs a node server. Webpack bundles the server into a single javascript file with an inline source map, that maps to source files in the workspace directory. First of all it seems like Indium does not have a way to specify if the source maps have an offset (like VS Code you specify `cwd` in the `launch.json`), and I'm not sure if it knows where my entry point is either (`./.build/server.js`).

I'm able to connect to node using `M-x indium-connect-to-nodejs` and the console pane works. But I can't set breakpoints with `indium-add-breakpoint`... emacs just outputs a bunch of nonsense text in a mini buffer. However, debugging server code works perfectly fine with VS Code.

Is this kind of setup not supported by Indium or am I doing something wrong?

Example repo including working vscode launch.json:
https://github.com/chris-kahn/hot-reload-all-the-things

**Comment by NicolasPetton** [comment]
Sourcemap support with webpack is new, and there might still be issues with it. Thanks for the link to a repo, I'll try to reproduce the problem and fix it!

**Comment by NicolasPetton** [comment]
Indeed, this kind of setup isn't yet supported (but it is planned).

However, there's a way to tell Webpack that it needs to use absolute paths:

```js
const webpack = require("webpack");
const path = require("path");
const nodeExternals = require("webpack-node-externals");
const StartServerPlugin = require("start-server-webpack-plugin");

const bannerOptions = {
    raw: true,
    banner: 'require("source-map-support").install();'
};

module.exports = {
    devtool: "inline-source-map",
    entry: [ "webpack/hot/poll?1000", "./server/index" ],
    watch: true,
    target: "node",
    externals: [ nodeExternals({ whitelist: [ "webpack/hot/poll?1000" ] }) ],
    module: {
        rules: [
            { test: /\.js?$/, use: "babel-loader", exclude: /node_modules/ },
        ],
    },
    plugins: [
        new StartServerPlugin({ name: "server.js", nodeArgs: ["--inspect"] }),
        new webpack.NamedModulesPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoEmitOnErrorsPlugin(),
        new webpack.DefinePlugin({
            "process.env": { BUILD_TARGET: JSON.stringify("server") }
        }),
        new webpack.BannerPlugin(bannerOptions)
    ],
    output: {
		path: path.join(__dirname, ".build"),
		filename: "server.js" ,
		devtoolModuleFilenameTemplate: '[absolute-resource-path]'
	}
};
```

This example is taken from your repository, I simply added `devtoolModuleFilenameTemplate: '[absolute-resource-path]'` to it.

Indium is then able to debug it properly.

**Comment by NicolasPetton** [comment]
I mentioned this configuration option is the documentation: https://indium.readthedocs.io/en/latest/debugger.html#sourcemaps-and-webpack

**Comment by chris-kahn** [comment]
Great, although even with the sourcemaps using absolute paths I still can't add breakpoints. This is what it looks like when I try: 

<img width="1280" alt="screenshot at dec 01 14-50-55" src="https://user-images.githubusercontent.com/16520875/33488211-e3f399fe-d6a7-11e7-8c14-b9e9d2afa0c2.png">

**Comment by NicolasPetton** [comment]
Wow, that's weird, I have never seen this.

In the *messages* buffer, can you find the beginning of this output? Maybe there's something interesting there.

Also, could you tell me which version of Indium you are using? A recent commit in Indium added support for data uri sourcemaps https://github.com/NicolasPetton/Indium/pull/128

**Comment by NicolasPetton** [comment]
I checked from your screenshot, and it looks like it's the sourcemap that you see. After updating Indium, the debugger should work ™️

**Comment by chris-kahn** [comment]
Ohhh is this due to specifying inline source maps? It seems like that base64 payload is probably the what webpack is returning for the sourcemap path.

<img width="1000" alt="screenshot at dec 01 15-42-12" src="https://user-images.githubusercontent.com/16520875/33490203-44fb1c3a-d6ae-11e7-9775-fd56b828bede.png">

**Comment by NicolasPetton** [comment]
Exactly! The latest version of Indium should handle this perfectly well.

**Comment by NicolasPetton** [comment]
@chris-kahn can you confirm that the latest version of Indium works for you as well?

**Comment by chris-kahn** [comment]
I've just tested it now and yep, the latest version is working! I hadn't updated in a few weeks and it seems you were way ahead of me. Thanks, now I can use it and create some more issues for you!

**Comment by NicolasPetton** [comment]
Awesome! Open as many tickets as you need :-)
