### ISSUE TITLE
Non interactive way to connect to chrome tab?

### ISSUE THREAD

**Issue by sandric** [NicolasPetton/Indium#134]
I'm little lost in source code with different callbacks, maybe somebody could walk me through my question. I wish to write an elisp function that will automate all `indium-connect-to-chrome` routine. It will accept ip address of running chrome server, port and full url of tab I want connect to. Is there a way to do that and what function should I look at?

**Comment by NicolasPetton** [comment]
There's no way currently to do that, unfortunately.

**Comment by diasbruno** [comment]
@NicolasPetton Can you give some direction on how we could implement such a functionality? Perhaps parsing a full url...
