### ISSUE TITLE
Is it possible to connect to a react-native packager process?

### ISSUE THREAD

**Issue by LaloHao** [NicolasPetton/Indium#138]

**Comment by NicolasPetton** [comment]
I have no idea, as I never tried to do that myself. If you can give me pointers, I will investigate though.

**Comment by NicolasPetton** [comment]
@LaloHao do you have any pointers to get me started? I'd like to give it a try, and see what could be missing in Indium to support react-native.

**Comment by ag91** [comment]
@NicolasPetton if you are still interested, I think this conversation may be of interest: https://github.com/thheller/shadow-cljs/issues/214#issuecomment-381326074
As I understand it, that is how ClojureScript interacts with the react-native emulator (basically loading the JS bundle in the repl before it is fed to the emulator).

Anyway great job with Indium :D
