### ISSUE TITLE
Request: Using an overlay when debugging

### ISSUE THREAD

**Issue by jojojames** [NicolasPetton/Indium#139]
Hi, was wondering if we could get an overlay similar to cider when debugging.

```
(defun indium-debugger-refresh-echo-area ()
  "Refresh the echo area as motion commands clear the echo area."
  (message indium-debugger-message))

```

The debugger message gets cleared pretty often with eldoc in play.

I think cider-debug https://github.com/clojure-emacs/cider/blob/master/cider-debug.el provides an option to switch between the two.

Thanks!

**Comment by NicolasPetton** [comment]
That would indeed be neat.
Do you want to give this feature a shot?

**Comment by jojojames** [comment]
I'll give it a shot once I find some free time. :)

**Comment by NicolasPetton** [comment]
The feature seems pretty easy to implement (understand steal from CIDER :stuck_out_tongue_winking_eye:), but I'm not sure where to place it.

I see two options:

- just above the line of the current stack frame
- just above the current function

I guess the first option is the best one, but I'm interested in others opinions. (/cc @DamienCassou who might be interested in this).

**Comment by jojojames** [comment]
+1 on current line.

**Comment by DamienCassou** [comment]
CIDER seems to place it above current function: https://cider.readthedocs.io/en/latest/debugging/. This is nice because the function text is not changed each time the active line of code changes. Another position could be the window's first line so the overlay is always found at the same position.

Nevertheless, I don't care that much because I now remember the shortcuts and don't need to see them anymore.

**Comment by NicolasPetton** [comment]
Damien Cassou <notifications@github.com> writes:

> CIDER seems to place it above current function:
> https://cider.readthedocs.io/en/latest/debugging/. This is nice
> because the function text is not changed each time the active line of
> code changes. Another position could be the window's first line so the
> overlay is always found at the same position.

The difference between Clojure and JavaScript is that in JavaScript it
can be hard to tell what is "the current function", so I thought that
above the current line was a better solution.

However is can be annoying as you suggest. I'll give it a try.

**Comment by NicolasPetton** [comment]
What about using a header instead?

**Comment by NicolasPetton** [comment]
Now that I think about it, what about using a header instead?
