### ISSUE TITLE
Show confirmation or error message in REPL buffer after eval

### ISSUE THREAD

**Issue by ivo-** [NicolasPetton/Indium#143]
Currently only `indium-eval-last-node` and `indium-eval-defn` show error or result from the evaluation. It will be great if all the evaluation commands like `indium-eval-buffer` or `indium-eval-region` show some confirmation/error message after evaluation. Also showing the code that is evaluated and context in the REPL buffer will be great. I am testing with node.js connection. 

Great work, thank you!

**Comment by NicolasPetton** [comment]
Hi!

Isn't the output in the echo area enough? If you need to inspect the result, you can always do `C-c M-i`.
I'm afraid that this would pollute the REPL buffer with a lot of output (I'm a heavy user of `indium-eval-*`.

**Comment by ivo-** [comment]
Hi! For `indium-eval-last-node` and ` indium-eval-defn` it is enough, but `indium-eval-buffer` and `indium-eval-region` don't show any output in echo area or the REPL and you never know if the code is actually evaluated successfully or not. My personal taste is to  show evaluated code in REPL, as it is nice to have a history of everything evaluated. This seems to be the approach I am used to from other similar tools, but I won't hurt if it is optional.

**Comment by NicolasPetton** [comment]
@ivo- Indium nowadays shows the result of the evaluation for both `indium-eval-buffer` and `indium-eval-region`, so I'm closing this issue.
