### ISSUE TITLE
Breakpoints not breaking

### ISSUE THREAD

**Issue by UnderSampled** [NicolasPetton/Indium#144]
At the moment, none of my breakpoints seem to do anything, even though I can confirm I am connected to the node process (files show up in indium-list-scripts, the REPL responds, and it breaks on the first line even though I don't have indium-nodejs-inspect-break set). Any breakpoint I add -- while connected, before connecting, or trying again after reconnecting -- does not stop execution.

I usually am running electron, but I created this to test, with the same results running just node: 
```
const a = 1
let b = 2
b = a + 4
console.log(a+b)
```
If I try to step over from that automatic break, it skips over everything and says "Exception in websocket callback! (end-of-buffer)"

**Comment by NicolasPetton** [comment]
I can reproduce the bug on Windows only.

**Comment by NicolasPetton** [comment]
The latest revision on master should fix the issue. Please tell me if it's still a problem for you.

**Comment by UnderSampled** [comment]
Works! Thank you!
