### ISSUE TITLE
Reuse existing window when debugger stops

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/Indium#148]
1. get 2 windows with JS code in one and chromium in the other
2. add a breakpoint in the visible JS code
3. refresh chromium page

I expect that the JS window gets focus and that chromium is still visible. However, very often, I get 2 windows both showing the same JS buffer. Chromium is not visible anymore.

**Comment by NicolasPetton** [comment]
That's because you're using EXWM, so the current buffer in Emacs is Chromium when Indium's debugger is hit.

I don't think there's anything wrong with the current behavior, so I'm closing this issue.
