### ISSUE TITLE
Passing environment variables to node command fails

### ISSUE THREAD

**Issue by baerrach** [NicolasPetton/Indium#150]
If you want to pass environment variables to the node script you would normally do

`MY_ENV="SOME VALUE" node <command>`

However `indium-nodejs--add-flags` in `indium-node.el` assumes the first argument of the command is the program to run, returning a value like

`MY_ENV="SOME VALUE" --inspect node <command>`

instead of 

`MY_ENV="SOME VALUE" node --inspect <command>`

I am working around this by using elisp to initalise the value

`(setenv "MY_ENV" "SOME VALUE")`

**Comment by NicolasPetton** [comment]
Should be fixed in master!
