### ISSUE TITLE
allow `await` in REPL

### ISSUE THREAD

**Issue by baerrach** [NicolasPetton/Indium#151]
I doesn't appear that Node will support this natively, see https://github.com/nodejs/node/issues/13209

However you can hack this inside indium by wrapping await code in an async function.

I've had to throw away const/let definitions as the variable needed to be in global scope to be assigned a value.

This is super useful for using `indium-eval-last-node` ( <kbd>CTRL</kbd>+<kbd>x</kbd> <kbd>CTRL</kbd>+<kbd>e</kbd>) in your existing code without having to manually wrap it.

You can then go back to your indium debugger buffer and `indium-debugger-resume` (<kbd>c</kbd>) to continue your debug repl loop. You will often need multiple runs through your debug repl loop so the promise queues can get drained.

```
(defun bae/indium-backend-evaluate (orig-indium-backend-evaluate backend string &optional callback)
  (when (string-match-p "^\\(const\\|let\\)\\W*" string)
    (setq string (replace-regexp-in-string "^\\(const\\|let\\)\\W*" "" string)))

  (when (string-match-p "^\\(\\w+\\W*=\\)?\\W*await" string)
    (message "Wrapping javascript in async block")
    (setq string (format "(async () => {%s; console.log('Wrapped async completed.');})();" string)))

  (funcall orig-indium-backend-evaluate backend string callback)
  )

(advice-add 'indium-backend-evaluate :around #'bae/indium-backend-evaluate)
```

**Comment by NicolasPetton** [comment]
Thanks, this is a nice hack, but not something I'd be willing to include in Indium though.
