### ISSUE TITLE
SourceMap with rewritten url

### ISSUE THREAD

**Issue by gburch** [NicolasPetton/Indium#153]
I may have missed this in the docs, so I apologize if I did. I have an app that is served through a rewritten url, the most basic part of this is it adds a directory _m/_ in front of all my source files. I attempted to work around this my simply creating a symlinked dir following this scheme but it did not work. Example dir structure and url structure:

Url:
mysite.com/m/scripts/app.js

On Disk:
~/site/somerepo/app/scripts/app.js

Symlink: 
ln -s app m

It sometimes acts if it is working but never hits breakpoints and most of the time says it failed to place a breakpoint. Additionally it seems somehow emacs is expanding the symlink at times which could be part of the problem, when I got back to open the buffer it has _app_ instead of _m_ even though I opened the file from _m_

Is there a better way to resolve this without symlinks?

**Comment by NicolasPetton** [comment]
Thanks for reporting the issue!

IIUC you are *not* using sourcemaps, right?

**Comment by gburch** [comment]
I am using gulp sourcemaps.

**Comment by NicolasPetton** [comment]
Then you'll have to wait a bit for Indium to support such cases. Sourcemap support is still quite basic, and I went around rewrite rules with Webpack by emitting absolute paths in sourcemaps.

It's in the works though, so hopefully you won't have to wait long. I'll keep this issue open in the meantime.

**Comment by gburch** [comment]
Did you have an idea for an approach? It may be something I can submit a PR for if you have a basic approach in mind.

**Comment by chris-kahn** [comment]
It would be nice if we could configure everything via a config file similar to how VS Code is doing it:

```
{
            "name": "project-a chrome attach",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "webRoot": "${workspaceRoot}/apps/project-a/src",
            "url": "http://localhost:8082/en-gb/account", 
            "sourceMaps": true,
            "smartStep": true,
            "skipFiles": [
                "node_modules/**"
            ],
            "sourceMapPathOverrides": {
                "webpack:///./*": "${webRoot}/*",
                "webpack:///*": "*",
                "webpack:///./~/*": "${workspaceRoot}/node_modules/*"
            }
        }
```

**Comment by NicolasPetton** [comment]
Christopher <notifications@github.com> writes:

> It would be nice if we could configure everything via a config file
> similar to how VS Code is doing it:

That's exactly what I'm working on.  I'll push a branch soonish :)

**Comment by NicolasPetton** [comment]
The changes have landed in master https://indium.readthedocs.io/en/latest/setup.html :)
