### ISSUE TITLE
Downloading remote sourcemap files is really slow

### ISSUE THREAD

**Issue by chris-kahn** [NicolasPetton/Indium#156]
For example my project includes a few scripts hosted in Amazon S3, and when connecting to Chrome, Emacs will completely freeze while downloading these sourcemap files for a good 1-2 minutes. Any idea why? VS Code doesn't seem to have any problems with this and starts debugging almost instantly.

**Comment by NicolasPetton** [comment]
Christopher <notifications@github.com> writes:

> For example my project includes a few scripts hosted in Amazon S3, and
> when connecting to Chrome, Emacs will completely freeze while
> downloading these sourcemap files for a good 1-2 minutes. Any idea
> why? VS Code doesn't seem to have any problems with this and starts
> debugging almost instantly.

That's a known issue, but I'm delaying it until we have a configuration
file similar to VSCode, it's currently my top priority.

**Comment by NicolasPetton** [comment]
Hi! 

The new version on master (which has a lot of changes, see here https://emacs.cafe/emacs/javascript/indium/2018/08/14/indium.html) should fix the issue.

**Comment by chris-kahn** [comment]
That's great! Thanks! I will try it out.

**Comment by chris-kahn** [comment]
Everything works very fast now! 👍

**Comment by NicolasPetton** [comment]
Awesome, I'm glad it made a difference for you as well.
