### ISSUE TITLE
No Indium Connection with chrome backend

### ISSUE THREAD

**Issue by MartyNeal** [NicolasPetton/Indium#159]
### Description ###
Looks like `indium-current-connection` never gets set after connecting to a chrome tab, and thus, attempts to execute commands fail with the message `No Indium Connection`.  This is/was working before updating to this version.

### Reproduction Steps: ###
1. Open a chrome instance with remote debugging port
2. With a minimal indium.json config in the cwd `{ "configurations": [ { "name": "Webar", "type": "chrome" } ] }`
3. From a indium-interaction-mode buffer, run `M-x indium-connect`
4. Select tab from list of tabs
5. No errors, or indication that anything failed
6. just after a `1+1;` statement, run `M-x indium-eval-last-node`.  
7. Observer the message `No Indium Connection` in the *Messages* buffer

### Environment ###
* Indium Version: 20180727.1533
* Chrome Version: 67
* Emacs Version: 26.1

PS. Indium is just an **AWESOME** bit of software

**Comment by MartyNeal** [comment]
Just realized that a new version: 20180731.808 is available, but still also seems to have the above problem

**Comment by NicolasPetton** [comment]
Hi! 

The new version on master (which has a lot of changes, see here https://emacs.cafe/emacs/javascript/indium/2018/08/14/indium.html) should fix the issue.
