### ISSUE TITLE
Support for chromium-browser 

### ISSUE THREAD

**Issue by olymk2** [NicolasPetton/Indium#162]
Currently it looks for chrome and chromium but on all my systems its actually called chromium-browser so it fails to launch because it cant find the binary.

error in process filter: user-error: Cannot find chrome/chromium binary (chromium) in PATH
error in process filter: Cannot find chrome/chromium binary (chromium) in PATH

I don't have google chrome installed currently but i believe that has a binary name of google-chrome.

This is on linux based systems.

**Comment by NicolasPetton** [comment]
You can customize `indium-chrome-executable` and set it to `chromium-browser`.

**Comment by bigfish** [comment]
as an addendum, setting the indium-chrome-executable to 'google-chrome' worked for me, having installed Chrome on ubuntu.
