### ISSUE TITLE
error in process filter: Indium server process error: env: node: No such file or directory

### ISSUE THREAD

**Issue by chris-kahn** [NicolasPetton/Indium#165]
Any idea what can be causing this?

Node and Indium are both available on my PATH...

**Comment by NicolasPetton** [comment]
What is your operating system?
What does your .indium.json file looks like?

**Comment by chris-kahn** [comment]
The problem was due to my emacs paths... by default in macOS emacs does not properly load user profiles to get environment variables. I've solved it by using this plugin in emacs:

```
   dotspacemacs-additional-packages
   '(
     indium
     exec-path-from-shell
    )
```

And then in my user-config:

```
  (when (memq window-system '(mac ns x))
    (exec-path-from-shell-initialize))
```

And now it picks up my `.zshenv` file.

**Comment by NicolasPetton** [comment]
I think it would be worth mentioning in the troubleshooting section of the manual https://indium.readthedocs.io/en/latest/troubleshooting.html
