### ISSUE TITLE
Sometimes I can't quit the debugger

### ISSUE THREAD

**Issue by aaronjensen** [NicolasPetton/Indium#166]
First of all, wow. What an incredible tool. Thank you!

Within a React component's render method, when I place a breakpoint, I can successfully break at that point.

Once I'm there, however, the debugger doesn't appear to work as I'd expect. Continue appears to continue, but because another render happens it breaks immediately again. I continue to continue until no more renders occur. The browser is responsive, but indium still thinks I'm in debugger mode. 

There's not much I can do to get out of it other than issue another indium connect and kill my buffer and reopen it. 

I can't repro this just by placing my breakpoint in a function that is called multiple times, it seems specific to this react render function.

I can potentially work on a repro, but I wanted to post this in case it's obvious what's going on here.

Thanks!

**Comment by NicolasPetton** [comment]
Aaron Jensen <notifications@github.com> writes:

> First of all, wow. What an incredible tool. Thank you!

Thanks!

> Within a React component's render method, when I place a breakpoint, I can successfully break at that point.
>
> Once I'm there, however, the debugger doesn't appear to work as I'd expect. Continue appears to continue, but because another render happens it breaks immediately again. I continue to continue until no more renders occur. The browser is responsive, but indium still thinks I'm in debugger mode. 
>
> There's not much I can do to get out of it other than issue another
> indium connect and kill my buffer and reopen it.

Does disabling breakpoints help?  It's not a proper solution, but it
can help me understand the issue.

> I can't repro this just by placing my breakpoint in a function that is
> called multiple times, it seems specific to this react render
> function.

Ok, that's already a starting point.

> I can potentially work on a repro, but I wanted to post this in case
> it's obvious what's going on here.

No, nothing that I can think of. If you could give me a recipe to
reproduce the problem, I'll certainly try to understand the issue and
fix it.

Cheers,
Nico

**Comment by aaronjensen** [comment]
> Does disabling breakpoints help?  It's not a proper solution, but it
> can help me understand the issue.

It doesn't seem to, it's stuck in the debugging mode (the caret is pointing at the line where it initially broke and it's showing instructions in the modeline).



> No, nothing that I can think of. If you could give me a recipe to
> reproduce the problem, I'll certainly try to understand the issue and
> fix it.

I'll see what I can do. Are there any debugging/troubleshooting steps you could think of that I could try? I'm somewhat capable of elisp debugging., but it'd be great to have a starting point, especially since there could be a problem in the server in this case.

**Comment by NicolasPetton** [comment]
There are instructions here https://indium.readthedocs.io/en/latest/troubleshooting.html#general-advices-before-reporting-issues

But I suspect that the TCP messages are not handled correctly. Can you paste the content of the ` indium-client-conn ` (notice the spaces around the buffer name) as well?

**Comment by NicolasPetton** [comment]
I found a bug that looks very close to the symptoms you describe, without using React. Unfortunately it's pretty hard to reproduce.

**Comment by aaronjensen** [comment]
I can't reproduce it with the `(delete-char 1)` you added in that commit. I don't know if you intended to fix it with that, but it looks like you did 😄 Thanks!

I'll reopen if I see it again.

**Comment by NicolasPetton** [comment]
that's odd, but good :)
