### ISSUE TITLE
Can't get the value of a local variable not in top stack frame

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/Indium#167]
```javascript
f() {
    var foo = 'rstiraestnrst';
    g();
    return foo;
}

g() {
   throw new Error('error')
}

f();
```

Execute this with indium. You should get a debbuger within `g()`. If you go to previous frame, you should be able to get a value for variable `foo` by typing `C-x C-e` but that doesn't work

> ReferenceError: foo is not defined

Workaround: type `C-c C-l` instead to get all local variables.

**Comment by NicolasPetton** [comment]
You're right, and that is a regression in the new client/server implementation.
It's not super high priority though compared to some more urgent bugs, but I'll try to add support for it soonish.

**Comment by DamienCassou** [comment]
Fix at https://gitlab.petton.fr/nico/Indium/merge_requests/27.
