### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by bobrowadam** [NicolasPetton/Indium#168]
Hi, While running 'indium-connect' I get `connect ECONNREFUSED 127.0.0.1:9229` although this port is not being used by any process.
BTW - thanks for all your great work!
Here is the indium log:
```
Sent: ((id . 1) (type . configurations) (payload (action . list) (directory . /Users/bob/source/simple-node-prjct/)))

Received: ((id . 1) (type . success) (payload . [((name . simple-node-prjct) (type . node) (command . node ./app.js) (inspect-brk . t) (projectFile . /Users/bob/source/simple-node-prjct/.indium.json) (resolvedRoot . /Users/bob/source/simple-node-prjct))]))

Sent: ((id . 2) (type . connection) (payload (action . connect) (directory . /Users/bob/source/simple-node-prjct/) (name . simple-node-prjct)))

Received: ((id . 2) (type . error) (payload (error . connect ECONNREFUSED 127.0.0.1:9229)))

Received: ((id . 2) (type . success) (payload . Connected to Node!))

Sent: ((id . 3) (type . runtime) (payload (action . evaluate) (expression . 1)))

Received: ((id . 3) (type . error) (payload (error . Not connected)))

Sent: ((id . 4) (type . runtime) (payload (action . evaluate) (expression . console.log(1))))

Received: ((id . 4) (type . error) (payload (error . Not connected)))

```

**Comment by NicolasPetton** [comment]
@bobrowadam can you tell me a bit more about your setup?

- NodeJS version
- How you start node
- .indium.json file contents could help as well

Thanks!

**Comment by bobrowadam** [comment]
Hey, I eventually managed to make it work so closing the issue.
Thanks!

**Comment by NicolasPetton** [comment]
bobrowadam <notifications@github.com> writes:

> Hey, I eventually managed to make it work so closing the issue.

Cool! Could you tell me what was wrong?

Cheers,
Nico

**Comment by juergenhoetzel** [comment]
> Cool! Could you tell me what was wrong? Cheers, Nico

I had the same issue in an command line application. I was assuming `--inspect-brk` is used (like mentioned in the documentation):  [Fix invalid default value in documentation](https://github.com/NicolasPetton/Indium/pull/174)

**Comment by bobrowadam** [comment]
Honestly, I don't remember what solved it :) Might be what @juergenhoetzel had mentioned, not sure though.
