### ISSUE TITLE
Display Set elements

### ISSUE THREAD

**Issue by felipeochoa** [NicolasPetton/Indium#169]
In both the REPL and the inspector buffer, ES6 sets are shown as empty:

```
js> new Set([1, 2])
Set(2) {  }
```
```
Set(2)

  Symbol(Symbol.toStringTag): "Set"

  Symbol(Symbol.iterator): function
  __defineGetter__: function
  __defineSetter__: function
  // etc
  values: function
```

I realize this probably requires special-casing in the inspector, but it's really helpful to see set elements. Node's REPL does this:

```
> new Set([1, 2])
Set { 1, 2 }
```

**Comment by NicolasPetton** [comment]
Thanks for reporting this! :+1: 

I'll have a look and fix it, displaying data as close as possible to Node/Chromium.

**Comment by xuchunyang** [comment]
And Map

```
js> new Map([[1, 'one'], [2, 'two']])
Map(2) {  }
js> 
```

v.s. Node's

```
> new Map([[1, 'one'], [2, 'two']])
Map { 1 => 'one', 2 => 'two' }
>
```

**Comment by NicolasPetton** [comment]
Version 3.1 of the indium server should fix the issue! https://www.npmjs.com/package/indium
