### ISSUE TITLE
Broke mocha.el

### ISSUE THREAD

**Issue by felipeochoa** [NicolasPetton/Indium#170]
I set up [mocha.el](https://github.com/scottaj/mocha.el/) to [use the indium debugger](https://github.com/scottaj/mocha.el/pull/56). That setup, however, relied on `indium-connect-to-nodejs`: mocha.el needs to start the node process itself (setting a bunch of flags depending on the specific test/module/project being debugged) and then calls a debugger to attach to the process.

Is there a way to recover this functionality with the new structure?

**Comment by NicolasPetton** [comment]
Felipe <notifications@github.com> writes:

> Sure! Would you mind just throwing down a couple of bullets on what
> might need to change? The codebase has changed quite a bit since I
> last mucked around in it :)

Sure. Basically, you need to feed the server with an indium configuration that
you would generate on the fly.

You will probably want to configure the nodejs options as documented
here:
https://indium.readthedocs.io/en/latest/setup.html#nodejs-configuration-options

The server protocol is documented here:
https://github.com/NicolasPetton/Indium/tree/master/server

**Comment by NicolasPetton** [comment]
If you get stuck, ping me, I'll try to free some time to do it.

**Comment by NicolasPetton** [comment]
@felipeochoa did you manage to fix the issue? Any more help needed from me?

**Comment by felipeochoa** [comment]
Haven't had much time for OSS lately, so unfortunately not. It's still on my TODO list, though!

**Comment by NicolasPetton** [comment]
Felipe <notifications@github.com> writes:

> Haven't had much time for OSS lately, so unfortunately not. It's still
> on my TODO list, though!

Ok, just let me know if you need my help.
