### ISSUE TITLE
Indium server error: connect ECONNREFUSED 0.0.0.0:9222

### ISSUE THREAD

**Issue by manateelazycat** [NicolasPetton/Indium#171]
Hi

I have install indium with 
```
npm install -g indium
```

Below is .indium.json place on root of rails project:
```
{
    "configurations": [
	{
	    "name": "Tower NG",
	    "type": "chrome",
	    "host" : "0.0.0.0",
	    "url" : "http://0.0.0.0:3000",
	    "port" : 9222
	}
    ]
}
```

command indium-launch works fine, i got error after later:
```
Indium server error: connect ECONNREFUSED 0.0.0.0:9222
```

Below is content from *indium-debug-log*
```
Sent: ((id . 40) (type . configurations) (payload (action . list) (directory . /Users/andy/tower-ng/)))

Received: ((id . 40) (type . success) (payload . [((name . Tower NG) (type . chrome) (host . 0.0.0.0) (url . http://0.0.0.0:3000) (port . 9222) (projectFile . /Users/andy/tower-ng/.indium.json) (resolvedRoot . /Users/andy/tower-ng))]))

Sent: ((id . 41) (type . connection) (payload (action . connect) (directory . /Users/andy/tower-ng/) (name . Tower NG)))

Received: ((id . 41) (type . error) (payload (error . connect ECONNREFUSED 0.0.0.0:9222)))
```

What's wrong with my config? 

How can i fix it? 

Thanks for help. ;)

**Comment by NicolasPetton** [comment]
Hi!

It looks like Chrome is not started with the `--remote-debugging-port=9222` flag.
You can check by navigating to `localhost:9222`.

One possibility is that Chrome was already running when you launched Indium, in which case it might just open a new tab and not start a new instance.

Can you try closing Chrome first? If it works but is inconvenient, we can think about ways to fix it.

**Comment by manateelazycat** [comment]
@NicolasPetton 

I didn't realize Google Chrome still contains background process even I quit Chrome from GUI.
I can use indium-connect command after i killall Chrome processes.

Thanks so much for build indium, it's really cool that i can evaluate JavaScript in Emacs !!!

Have a nice day, man! ;)

 -- Andy

**Comment by NicolasPetton** [comment]
@manateelazycat thanks :)

As I said, if having to kill Chrome turns out to be annoying, I can work on a fix.

**Comment by NicolasPetton** [comment]
@manateelazycat What about using a separate Chrome profile?

**Comment by manateelazycat** [comment]
sorry，i can't understand what you mean :(

I can help test if you have new solution

**Comment by manateelazycat** [comment]
@NicolasPetton

Of course, it's better if Chrome don't need user restart.

I think Chrome background process mechanism will confuse many people that wan't try indium.

**Comment by NicolasPetton** [comment]
With commit 6259454, Indium will start a new Chrome process in a separate profile by default, so no need to restart Chrome anymore.
