### ISSUE TITLE
Prompt while debugging vanilla JS code in Node

### ISSUE THREAD

**Issue by mfidemraizer** [NicolasPetton/Indium#172]
When I run `indium-debugger-launch` on a project where I use Node 10.x and vanilla ES modules, I get this prompt whenever I do any debugger action (step into, step out, resume...): 

https://github.com/NicolasPetton/Indium/blob/f19ea56a3825920df92609286d5caa2b8b946406/indium-debugger.el#L200

This is my `.indium.json` file:

```json
{
  "configurations": [
    {
      "name": "test shared",
      "type": "node",
      "port": 8585,
      "command": "node --experimental-modules --loader ./src/testing/testLoader.mjs --inspect=8585 ./spec/run.mjs",
      "inspect-brk": true
    }
  ]
}
```

**Comment by NicolasPetton** [comment]
Version 3.1.1 of the server component of Indium should fix the issue.

**Comment by mfidemraizer** [comment]
Yes, it does! Thank you for fixing the issue! Now Indium is also usable in vanilla JS ES modules!
