### ISSUE TITLE
Can you use js-mode instead js2-mode in indium?

### ISSUE THREAD

**Issue by manateelazycat** [NicolasPetton/Indium#176]
Hi 

I found js2-mode is very slow that will freeze Emacs when type chars in *.js file.

So can you use js-mode instead js2-mode in indium source code?

Thanks

**Comment by NicolasPetton** [comment]
Andy Stewart <notifications@github.com> writes:

> So can you use js-mode instead js2-mode in indium source code?

Yes you can.  There is a warning about it in the document of Indium:
https://indium.readthedocs.io/en/latest/debugger.html#using-sourcemaps

**Comment by manateelazycat** [comment]
> Andy Stewart <notifications@github.com> writes:
> So can you use js-mode instead js2-mode in indium source code?
> Yes you can. There is a warning about it in the document of Indium: https://indium.readthedocs.io/en/latest/debugger.html#using-sourcemaps

![image](https://user-images.githubusercontent.com/237487/45738587-7f467000-bc23-11e8-918f-d88d1211372b.png)

@NicolasPetton  I mean can you remove js2-mode from indium source code?

I even can't load indium success if i remove j2s-mode.el from load-path.

**Comment by NicolasPetton** [comment]
Why do you want to remove the dependency on js2-mode? 
Indium uses js2-mode to parse JS files and use the AST.

Loading js2-mode does not mean that you have to use that major mode for JavaScript buffers.

**Comment by manateelazycat** [comment]
ok i understand
