### ISSUE TITLE
Which javascript(s)?

### ISSUE THREAD

**Issue by vemv** [NicolasPetton/Indium#178]
Hi there!

Project looking very nice, kudos.

Reading the README/docs it is not clear to me which EcmaScript versions are supported, which are _best_ supported, which mode I should use (js-mode? js2-mode?)...

I'd suggest having a brief section dedicated to it.

Thanks - Victor

**Comment by NicolasPetton** [comment]
Thanks for the suggestion.

What exactly do you find confusing: the best Emacs major-mode to use, or the JS version that is supported (ES5, ES6, etc.)?

**Comment by vemv** [comment]
Thanks for the reply,

actually I have both questions.

**Comment by NicolasPetton** [comment]
Regarding ES versions, Indium is evaluating JavaScript in the runtime it connects to, so Indium actually doesn't know. 

I'll document major modes in the documentation. Both js-mode and js2-mode work. I would suggest using js-mode with js2-minor-mode, as it provides the fastest experience. There is a warning about js2-mode in the documentation here: https://indium.readthedocs.io/en/latest/debugger.html
