### ISSUE TITLE
`indium-launch` returns error

### ISSUE THREAD

**Issue by stephanschubert** [NicolasPetton/Indium#179]
I'm running `indium-launch`, a chrome tab is opened but the minibuffer says:

```
Indium server error: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /json/list</pre>
</body>
</html>
```

My app is running at:

```
ℹ ｢wds｣: Project is running at http://localhost:8080/
```

and my config is:

```
{
  "configurations": [
    {
      "name": "my-project",
      "type": "chrome",
      "root": "src",
      "host": "localhost",
      "url": "http://localhost:8080",
      "port": 8080
    }
  ]
}
```

What am I missing here?

**Comment by NicolasPetton** [comment]
Do you have Chrome already opened prior to running `indium-launch`? If so, it is probably started without the `--remote-debugging-port` flag, as explained here: https://indium.readthedocs.io/en/latest/setup.html.

I'm working on an improvement (start chrome with a new user profile),  but in the meantime you'll to either start chrome yourself with the flag, or make sure that chrome is not started when calling `indium-launch`.

**Comment by stephanschubert** [comment]
@NicolasPetton Ah thank you, I missed that. A custom profile would be nice too.

In case someone finds that issue later—I had to use the following command on OSX:

```
sudo /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome –remote-debugging-port=9222 https://localhost:3000
```
