### ISSUE TITLE
Script Completions in JS-REPL not working

### ISSUE THREAD

**Issue by stevemolitor** [NicolasPetton/Indium#183]
When I step thru my code using the indium debugger, completion does not work for any of my script variables. It only shows the default properties of `Object` in the completion list. The object inspector however can inspect my variables, showing all the properties of my object. 

Here is my script:

```js
var obj = { field1: 'one', fieldTwo: 'two ' };
debugger;
```

When I run my script and try to complete the properties of `obj` I only see the default `Object` properties:

<img width="322" alt="screen shot 2018-11-18 at 5 42 39 pm" src="https://user-images.githubusercontent.com/219235/48679722-62fa7d00-eb59-11e8-990b-82723326b98f.png">

Looking at `*indium-debug-log*`, I see that it only received the default `Object` properties from the `getCompletion` command:

```
Sent: ((id . 66) (type . runtime) (payload (action . getCompletion) (expression . obj)))

Received: ((id . 66) (type . success) (payload . [stack message constructor name toString __defineGetter__ __defineSetter__ hasOwnProperty __lookupGetter__ __lookupSetter__ isPrototypeOf propertyIsEnumerable valueOf toLocaleString]))
```

However when I inspect my object, I _do_ see the properties:

<img width="322" alt="screen shot 2018-11-18 at 5 42 39 pm" src="https://user-images.githubusercontent.com/219235/48679755-b240ad80-eb59-11e8-882a-95b6c8da3ce1.png">

I can see in `*indium-debug-log*` that that it _did_ correctly evalute `obj` and get back its properties when I ran inspect:

```
Sent: ((id . 92) (type . runtime) (payload (action . evaluate) (expression . obj) (frameId . {"ordinal":0,"injectedScriptId":1})))

Received: ((id . 92) (type . success) (payload (id . {"injectedScriptId":1,"id":76}) (type . object) (description . Object) (preview . { field1: "one", fieldTwo: "two " })))
```

So completion is not working when debugging, but inspection / evaluation is working.

Here is my `.indium.json`:

```json
{
  "configurations": [
    {
      "name": "node",
      "type": "node",
      "command": "node ./myscript.js",
      "inspect-brk": false
    }
  ]
}
```

According to my `indium.el`, the indium version is `1.2.0`. 
Emacs version is 26.1. 

```
 npm view indium version
3.3.1
```

```
node -v
v8.12.0
```

**Comment by NicolasPetton** [comment]
Thanks for reporting the issue. I can reproduce it as well.

**Comment by NicolasPetton** [comment]
Commit e6205659 should fix the issue.

**Comment by NicolasPetton** [comment]
@stevemolitor you'll also need to update the npm package to v3.3.3.
