### ISSUE TITLE
No JavaScript AST available

### ISSUE THREAD

**Issue by FrancescoCadei** [NicolasPetton/Indium#184]
`indium-run-node` works but when I try `C-x C-e` in a .js buffer i get `js2-node-at-point: No JavaScript AST available`

I'm with emacs 25.1.1, indium-1.2.0, node 10.13.0.

my settings:
```
(require 'indium)
(add-hook 'js-mode-hook #'indium-interaction-mode)
```

I don't have any other package for javascript.

Thanks in advance.

**Comment by NicolasPetton** [comment]
Francesco Cadei <notifications@github.com> writes:

> `indium-run-node` works but when I try `C-x C-e` in a .js buffer i get `js2-node-at-point: No JavaScript AST available`
>
> I'm with emacs 25.1.1 and indium-1.2.0.
>
> my settings:
> ```
> (require 'indium)
> (add-hook 'js-mode-hook #'indium-interaction-mode)
> ```

Have you enabled `js2-minor-mode`?  Without it you will have no AST, and
Indium cannot lookup the node to evaluate.

**Comment by FrancescoCadei** [comment]
Thanks, I've solved adding `(add-hook 'js-mode-hook 'js2-minor-mode)`
