### ISSUE TITLE
Question: `indium-launch` opens `url` but does not connect to the tab

### ISSUE THREAD

**Issue by stephanschubert** [NicolasPetton/Indium#187]
I have to run `indium-connect` afterwards to open a REPL in the context of the tab. 

Is this intended?

**Comment by NicolasPetton** [comment]
No, that's not intended at all, it should connect to the current tab (the only one if you ran `indium-launch` with the default settings.

Do you get any error or message?

**Comment by NicolasPetton** [comment]
Ok, then I think I know what's going on. Upon launching the browser, indium connect to the current tab. However in your case, you get a popup, and my guess is that the current tab is not yet the page you want to debug, but an extension.

Do you get this message for each startup of Chrome.

**Comment by stephanschubert** [comment]
Yes—because it's a new temporary profile each time, I guess.

**Comment by NicolasPetton** [comment]
Right. I do not have this popup on Linux though. Thanks for reporting this, I'll try to come up with a fix.

**Comment by NicolasPetton** [comment]
Stephan Schubert <notifications@github.com> writes:

> Yes—because it's a new temporary profile each time, I guess.

When using Chrome on Linux (and not chromium as I usually do), I see the
same popup. However, Indium correctly connects to the tab, so I need to
investigate more.

**Comment by bigfish** [comment]
So this is broken in Chrome, but works in Chromium

I think it should probably pass the --profile-directory=Default param to Chrome binary.. https://superuser.com/questions/377186/how-do-i-start-chrome-using-a-specified-user-profile

syntax is a bit different on mac vs linux. Maybe an option to set profileDirectory in .indium.json ? But setting default by default would seem to make sense.

**Comment by bigfish** [comment]
wait.. it is only broken with temp profile.. I set 
  (setq indium-chrome-use-temporary-profile nil)
and it opened up Chrome without the popup, in current instance of Chrome.
 But there was an error about failing to connect..  but then if I quit Chrome entirely, and launch from emacs, indium connects fine to the launch page. 
I believe this is already documented.. but it would be nice if a) using temp profile actually worked in Chrome (see above suggestion) & b) if it could connect to running instance of Chrome (think I saw an isse for that).

**Comment by NicolasPetton** [comment]
@bigfish you are right, thank you.
I'll push a fix in master.

**Comment by NicolasPetton** [comment]
@bigfish I still cannot reproduce the issue on Linux, but maybe you can help me :)

Could you try the branch https://github.com/NicolasPetton/Indium/tree/fix-187 and tell me if it fixes your issue?

Basically what it does is use a directory inside `.emacs.d` as data dir for chrome by default.

**Comment by NicolasPetton** [comment]
@bigfish I opened a PR #210 which I think fixes your isssue.
