### ISSUE TITLE
mapping "localhost:8443/bat/quux.js/98234234" to "foo/bar/bat/quux.js"

### ISSUE THREAD

**Issue by arthurgleckler** [NicolasPetton/Indium#188]
I'm trying to figure out how to use source map overrides to map relative URLs that end with numbers to filenames without those numbers.  (The numbers are used to ensure uniqueness when the JavaScript sources change.)  For example, I'd like to map:

  `localhost:8443/bat/quux.js/98234234`

to:

  `foo/bar/bat/quux.js`

Is there a way to do this, perhaps with `sourceMapPathOverrides`?

Thank you very much.

P.S.: Indium is amazing, and I'm thrilled to have found it.  It should make debugging JavaScript much more pleasant.  If I can just get past this one issue, I can switch completely from Chrome's built-in debugger.  Thanks again.

**Comment by NicolasPetton** [comment]
`sourceMapPathOverrides` would only work if you are actually using sourcemaps, but it looks like you just want to map file paths, am I correct?

**Comment by arthurgleckler** [comment]
That's right.  I was hoping there might be a way to use the overrides
somehow.

**Comment by NicolasPetton** [comment]
Ok, then there's no support today for it, but I think we can easily add it.
How do you add the numbers to the file paths to be served?

I'm asking because I believe that using `localhost:8443/bat/quux.js?v=98234234` will work out of the box in Indium.

**Comment by NicolasPetton** [comment]
"Arthur A. Gleckler" <notifications@github.com> writes:

> The numbers are based on the file modification times of the `.js` files.
>
> I didn't want to change my approach, so I just temporarily hacked
> `resolveUrl` in `workspace.js` to remove the trailing numbers:

> ```
> 	let { protocol, pathname } = new URL(removeTrailingNumbers(url));
> ```
> and:
> ```
> const removeTrailingNumbers = (url) => {
>         let match = /(.*)\/[0-9]+/.exec(url);
>         return (match == null) ? url : match[1];
> }
> ```

We could add something like `sourcePathOverrides` to .indium.json for
that.  The issue with your approach is that it relies on internals of
the server, which my change at any time.

I think we could have a look at what options VisualStudio Code has,
maybe there's a good fit for us (.indium.json is loosely based on the
VSCode format).

> I also needed a way to map `.js` URLs to the corresponding files in my
> source code, which isn't a direct mapping.

Could you explain your need?

> For now, I just hacked a big `if-else` `switch` statement in a
> function called `mapScripts`, then called it from `resolveUrl`:

> ```
> 	return resolve(`${root}/${mapScripts(pathname)}`);
> ```
>
> This isn't a good long-term solution, but it let me get started with
> Indium.  I have to say, Indium is truly amazing!  The debugging tools
> in Chrome are already great, but having to use the Chrome UI, which
> requires lots of use of the mouse even with all the keyboard
> shortcuts, is a big drag on development efficiency.  Being able to use
> all the power of Emacs is absolutely fantastic.
>
> Thank you very much for Indium.

Thanks! I'm really glad you like it!

> If I think of a good, general solution to this problem, e.g. something
> involving recognizing a few new lines in `.indium.json`, I will submit
> a pull request.  I'm a fairly experienced JavaScript developer, but I
> do all my work in raw JavaScript, without any tools like Webpack,
> etc., so I don't know whether this is an issue that other people will
> have, too.

Cool, I'd be really happy to support your workflow.

**Comment by arthurgleckler** [comment]
Nicolas Petton <notifications@github.com> writes:

> We could add something like `sourcePathOverrides` to .indium.json for that. The issue with your approach is that it relies on internals of the server, which my change at any time.

Yes, of course.  It's definitely a hack.

> Could you explain your need?

For example, consider the script `calendar.js`, which is currently served by my app at the relative URL `/calendar/calendar.js/1542767747`.  The source file for that is at `web/site/private/calendar/calendar.js` relative to the root of my source tree, which is where my `.indium.json` file is located.  So I need to add the prefix `web/site/private/` even after I've removed the trailing slash and digits.  I could move `.indium.json` under `web/site/private/`, but that would break mappings from other URLs to their source files.

**Comment by arthurgleckler** [comment]
I've just sent you a pull request for this feature.

[pull request #191](https://github.com/NicolasPetton/Indium/pull/191)

Thank you!

**Comment by NicolasPetton** [comment]
Now that we have a proper solution in master, I'm closing this one :)
