### ISSUE TITLE
Unable to add/connect breakpoint in Express server functions

### ISSUE THREAD

**Issue by brandon-arnold** [NicolasPetton/Indium#189]
I mentioned this in Gitter and was asked to post a repro here.

When I set breakpoints inside my ExpressJS API callback functions, they have a red empty circle and do not seem to fire.

[See this repo](https://github.com/brandon-arnold/indium-reproduce-breakpoint-issue) in which I've implemented a simple Express server. Pull the repo down, `npm i && npm start`. Then browse to `./lib/foo/foo.js` in Emacs, perform `M-x indium-connect`, and try to set a breakpoint on `foo.js` line 2 for example.

**Comment by brandon-arnold** [comment]
Note: There is a little bit of extra stuff in that repo than necessary, namely the pulling in the Babel Namespaces plugin. I have left it there just in case that can be tested while you're at it; the error still happens if you change [the import in line 2 of `lib/lib.js` ](https://github.com/brandon-arnold/indium-reproduce-breakpoint-issue/blob/d650d91d76e71efd0d31abb5770a2cff9b8c32eb/lib/lib.js#L2) from:

```javascript
import foo from "./foo/foo";
```

to:

```javascript
import foo from "<libFoo>/foo";
```

**Comment by NicolasPetton** [comment]
@brandon-arnold Sorry for the late answer, are you still interested in seeing this issue fixed?

With the latest Indium from master, by changing 

```
import foo from "./foo/foo";
```

to:

```
import foo from "<libFoo>/foo";
```

Breakpoints work in `foo.js`.

I'm still investigating.

**Comment by NicolasPetton** [comment]
Also, without babel-plugin-namespaces, debugging in `foo.js` also works. I pushed an extra commit so you can try here https://github.com/NicolasPetton/indium-reproduce-breakpoint-issue.

I'm not exactly sure what's wrong with babel-plugin-namespaces, but the Chrome debugger can't find the source files either, and when debugging the source-mapping, I get invalid paths, which in turn result in invalid breakpoint locations.

**Comment by brandon-arnold** [comment]
> @brandon-arnold Sorry for the late answer, are you still interested in seeing this issue fixed?

Thanks for asking, @NicolasPetton; no, I have left that project where this was an issue.

**Comment by NicolasPetton** [comment]
Brandon Arnold <notifications@github.com> writes:

> Thanks for asking, @NicolasPetton; no, I have left that project where
> this was an issue.

Thanks. Are you using Indium on other JS projects?

**Comment by brandon-arnold** [comment]
> Thanks. Are you using Indium on other JS projects?

I am not at my current job! As I'm not working on any JS projects for which I'd be able to use it. I can definitely see debugging with Emacs down the road, though, if the opportunity arose.
