### ISSUE TITLE
Breakpoint not woking on nodejs

### ISSUE THREAD

**Issue by Yeonjj** [NicolasPetton/Indium#190]
Hi, 

A project is running on: 

spacemacs 26.1 on MacOS.

I am trying to set breakpoint connecting to node.js:

 1. On a terminal, I did `node --inspect --debug-brk app.js`.
 2. On spacemacs, I did `indium-connect-to-nodejs RET RET path RET y`
 3. It works fine until now. It breaks at first line.
 4. I did `indium-add-breakpoint` on a line I want to break
 5. hit `c` to continue and go to the line where I set the breakpoint 

But It doesn't stop there. It just resumes and finishes the debugging.
I've added an empty `.indium` file on the root folder, still doesn't work.

**Comment by NicolasPetton** [comment]
Hi!

Thank you for reporting the issue. I need some more information:

- Which version of Indium are you using?
- Do you have sourcemaps?
- Could you copy/paste your .indium.json file?

Thanks

**Comment by NicolasPetton** [comment]
"Y.H" <notifications@github.com> writes:

> Okay,
>  - I'm using indium-1.2.0.

Ok, then I think you should upgrade to indium 2.0.  Have a look at the
readme and https://emacs.cafe/emacs/javascript/indium/2018/08/14/indium.html

**Comment by NicolasPetton** [comment]
"Y.H" <notifications@github.com> writes:

>>The upcoming release of Indium will feature much better project configuration with sourcemap support for most, if not all JavaScript projects, including React, VueJS, Meteor, Angular, and basically any project that uses Webpack or other bundlers that produce sourcemaps.
>
> This is awesome! Thank you for the amazing work! 
> Can I use the features on the version 2.0.0?

Sure! v2.0.0 was released a few days ago!
