### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by artenator** [NicolasPetton/Indium#192]
When using indium with nodejs, I get this error when evaluating a buffer:
`ReferenceError: require is not defined
    at <anonymous>:1:1`

The breakpoints and the stepping debugger work fine, but I'm unable to evaluate `require` statements to the REPL.

**Comment by NicolasPetton** [comment]
Arte Ebrahimi <notifications@github.com> writes:

> When using indium with nodejs, I get this error when evaluating a buffer:
> `ReferenceError: require is not defined
>     at <anonymous>:1:1`

Thanks for reporting the issue.

Could you give me more info? Simple steps to reproduce the issue would be perfect.

**Comment by strawhatguy** [comment]
I've noticed this myself recently, when I have the node command in .indium.json be:
`node ./some.script.js`

it will load and execute the script just fine, but require won't be there.

However, if it's just:
`node`

Then obviously it doesn't load any scripts, but require is available.  So seems to be something about js and/or nodejs contexts that I don't understand.

**Comment by strawhatguy** [comment]
I just ran `node script.js --inspect` and connected a Chrome DevTools to it.  Didn't seem to have a require there either; so perhaps it's something about the dev tools protocol itself.

**Comment by strawhatguy** [comment]
Appears so, yes.  Do others see the same thing?

**Comment by NicolasPetton** [comment]
It probably has to do with the context used by Indium to evaluate in the REPL.

I will look for execution context events fired by the runtime. Currently Indium doesn't do anything with execution contexts outside of the debugger.

**Comment by NicolasPetton** [comment]
It turns out that using `includeCommandLineAPI` fixes the issue.

https://chromedevtools.github.io/devtools-protocol/v8/Runtime#method-evaluate

**Comment by NicolasPetton** [comment]
@artenator @strawhatguy Please try with the version 3.4.1 of the server component, I just published it on npm.
