### ISSUE TITLE
Trouble connecting to node

### ISSUE THREAD

**Issue by jcwearn** [NicolasPetton/Indium#194]
I am attempting to add indium to a node project.

The project has several different services that I have added to the configuration in the `.indium.json`:
```json
{
    "configurations": [
        {
            "name": "service-api",
            "type": "node",
            "command": "node",
            "port": 5864
        },
        {
            "name": "service-poller",
            "type": "node",
            "command": "node",
            "port": 5865
        },
        {
            "name": "service-processor",
            "type": "node",
            "command": "node",
            "port": 5863
        },
        {
            "name": "scratch",
            "type": "node",
            "command": "node"
        }
    ]
}
```

The three services are running in docker using commands similar to the following:
```
nodemon -L --inspect=0.0.0.0:5864 bin/www --watch /src
```

I can manually debug these services like so:
```
node inspect localhost:5864
```

When I attempt to connect using `indium-launch`, the port in my configuration seems to be ignored.
Regardless of which service I select, indium will start a node process listening on the default port `9229`.
```
Debugger listening on ws://127.0.0.1:9229/cbe68bd3-3c72-4714-b69e-4790bb9c93d3
For help, see: https://nodejs.org/en/docs/inspector
```

I also tried using `indium-connect` to connect to the running node processes and nothing seems to happen.

Interestingly, if I run `node inspect localhost:5864` as a separate process before running `indium-connect` the JS REPL will open and I will get an error saying `Indium server error: No inspectable targets`.  However, when I interact with the repl I get the following error: `Indium server error: Not connected`.

I added a "scratch" configuration that I can connect to if I just need a node repl or JS scratch buffer.  This works fine.

Is there something I am missing with the configuration of the other services?

**Comment by NicolasPetton** [comment]
Hi @jcwearn, here's what I did to reproduce the issue:

`test/test.js`:

```javascript
function foo() {
	console.log('foo');
	setTimeout(foo, 1000);
}

foo();
```

The `test/.indium.json` file:

```json
{
	"configurations":
	[
		{
			"name": "service-api",
			"type": "node",
			"command": "node ./test.js",
			"port": 5864
		}
	]
}
```

Then I start the node process with 

```sh
node --inspect=localhost:5864 ./test.js
```

and open an Indium connection through `M-x indium-connect`, it works fine.

However, if I use Indium to start the process, the port in the configuration indeed ignored.
Can you confirm that you experience the same behavior? Thanks!

**Comment by NicolasPetton** [comment]
@jcwearn Commit 8872448 should fix the issue. It'll land in master after the build.
