### ISSUE TITLE
Not sure how to run...

### ISSUE THREAD

**Issue by lrstott** [NicolasPetton/Indium#197]
My developement env is on a laptop running win 10 inside virtualbox running ubuntu 17.10. The vm is port forwarded because I run through a vpn. I am developing a react/redux application utilizing webpack and hot module replacement which works very well. However, I wanted to try indium to see if it would be better. I am running emacs 26.1.

I have tried several different ways of launching/connecting and have seen the REPL buffer but I do not get the "Welcome to Indium:" message and it does not seem to connect with the source files. And I am not sure how it would do that because with the hot swapping the built files are in memory and not on disk.

I typically run in my src dir " npm run start" which will build the app and launch chrome at which time I can open the debugger and get on with development. What do I need to do to utilize Indium?

**Comment by lrstott** [comment]
Continuing with debug, I am able to launch the node process with a command of 'node npm start'. And this did break in the npm-cli module butit does not find any sourcemaps.

**Comment by NicolasPetton** [comment]
lrstott <notifications@github.com> writes:

> Continuing with debug, I am able to launch the node process with a
> command of 'node npm start'. And this did break in the npm-cli module
> butit does not find any sourcemaps.

I'm not sure "node npm start" will work.

Have a look at the "start" command in you package.json.  From there you
should be able to see what node command to run from indium, and put it
in your .indium.json configuration file.

**Comment by lrstott** [comment]
The "npm start" is part of webpack and is utilizing, among other things, the hot package swap feature. The "start" is a script that sets many env vars and starts up several processes. It, in turn, is called by another script. I don't think it is a good idea to execute it directly.

The other issue I see with this is the fact that webpack is building the application in memory and not on disk (at least that is their description of the the process). Does indium have the ability to access the build in memory? 

I am wondering if what I really want to do is to "build" the source code which will create the map files, etc and then run indium on that. I am having a hard time wrapping my head around how to utilize this tool.

**Comment by NicolasPetton** [comment]
lrstott <notifications@github.com> writes:

> The "npm start" is part of webpack and is utilizing, among other
> things, the hot package swap feature. The "start" is a script that
> sets many env vars and starts up several processes. It, in turn, is
> called by another script. I don't think it is a good idea to execute
> it directly.

I see.

> The other issue I see with this is the fact that webpack is building
> the application in memory and not on disk (at least that is their
> description of the the process). Does indium have the ability to
> access the build in memory?

Yes, Indium works pretty well with webpack and sourcemaps in general,
see
https://indium.readthedocs.io/en/latest/debugger.html#using-sourcemaps.

**Comment by lrstott** [comment]
Ok, I have made some progress. 'list_script_sources' lists modules used in ./node_modules and from /usr/local/lib/node_modules. However, 'list_sourcemap_sources' returns nothing. I added the sourceMapPathOverrides with the settings you provided and that did not change anything which is what I expected.

**Comment by lrstott** [comment]
There is one thing I am confused about. In my source dir is a public dir with the index.html and there is also a src dir that contains the javascript source files. I set my "root" to "src". Is that the correct configuration?

**Comment by NicolasPetton** [comment]
lrstott <notifications@github.com> writes:

> There is one thing I am confused about. In my source dir is a public
> dir with the index.html and there is also a src dir that contains the
> javascript source files. I set my "root" to "src". Is that the correct
> configuration?

It depends where the .indium.json file is.  The root should be the the
directory where the source JS files are located, relative to the
.indium.json file.

**Comment by NicolasPetton** [comment]
lrstott <notifications@github.com> writes:

> There is one thing I am confused about. In my source dir is a public
> dir with the index.html and there is also a src dir that contains the
> javascript source files. I set my "root" to "src". Is that the correct
> configuration?

When in doubt, you can check the setup guide https://indium.readthedocs.io/en/latest/setup.html

**Comment by NicolasPetton** [comment]
@lrstott can I close the issue?

**Comment by lrstott** [comment]
Yes.On Jan 21, 2019 2:16 AM, Nicolas Petton <notifications@github.com> wrote:@lrstott can I close the issue?
