### ISSUE TITLE
How to run indium?

### ISSUE THREAD

**Issue by FinnFrotscher** [NicolasPetton/Indium#207]
The docs are not very clear on that.
I never worked with indium before, so please forgive the beginner-ishness of my question.

I have the `indium` npm and emacs packages installed. Do i need to run the npm package at a specific port? is it automatically run in the background by the emacs package?

This is the `.indium.json`.: 
```
{
    "configurations": [{
        "name": "app-api",
        "command": "babel-node src/index.js",
        "type": "node",
        "root": "src"
    }]
}
```

When running `M-x indium-connect` i receive a `connection refused 127.0.0.1:9229`. the docs say ` The --inspect flag will be added automatically.`. do i need to run a separate node process with a debugger?

**Comment by NicolasPetton** [comment]
Indium adds the arguments to the node call, but it will not work for babel-node.

You can however start the process, then connect to it using indium-connect.

If that's too inconvenient, we can think about it and try to find a better way.

On April 22, 2019 2:46:37 PM GMT+02:00, FinnFrotscher <notifications@github.com> wrote:
>The docs are not very clear on that.
>I never worked with indium before, so please forgive the
>beginner-ishness of my question.
>
>I have the npm package installed. Do i need to run it at a specific
>port? is it run in the background by the emacs package?
>
>This is the `.indium.json`.: 
>```
>{
>    "configurations": [{
>        "name": "app-api",
>        "command": "babel-node src/index.js",
>        "type": "node",
>        "root": "src"
>    }]
>}
>```
>
>When running `M-x indium-connect` i receive a `connection refused
>127.0.0.1:9229. the docs say ` The --inspect flag will be added
>automatically.`. do i need to run a separate node process with a
>debugger?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/NicolasPetton/Indium/issues/207

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by FinnFrotscher** [comment]
> You can however start the process, then connect to it using indium-connect.
How would I do that?

**Comment by NicolasPetton** [comment]
FinnFrotscher <notifications@github.com> writes:

> How would I do that?

You can start the node process with something like

node --inspect ./myfile.js

Then connect with M-x indium-connect (assuming you have a .indium.json
file in your project).

Nico

**Comment by NicolasPetton** [comment]
FinnFrotscher <notifications@github.com> writes:

> How would I do that?

In your case, it looks like

babel-node --inspect ...

should work.

**Comment by hamzakc** [comment]
@NicolasPetton 

I am in a similar situation. What would the .indium.json file look like ?

**Comment by NicolasPetton** [comment]
Until Indium supports `babel-node`, @FinnFrotscher & @hamzakc the solution should be to start babel-node manually with something like 

```
babel-node --inspect ...
```

And then use `M-x indium-connect` to connect to the running process.

The .indium.json file pasted by @FinnFrotscher is correct, but the `command` will not work, that's why I'm suggesting to start the `babel-node` process manually.

**Comment by NicolasPetton** [comment]
@FinnFrotscher @hamzakc With the latest commit (and update from MELPA in the next build), you should be able to use `babel-node` in place of `node`:

```json
{
    "configurations": [{
        "name": "app-api",
        "command": "babel-node src/index.js",
        "type": "node",
        "root": "src"
    }]
}
```

Then `M-x indium-launch` should just work.

Can you confirm that it works for you?
