### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by kiemdoder** [NicolasPetton/Indium#215]
When I try to evaluate something like
```
export function add(a, b){ return a + b }
```
with `M-x indium-eval-region` I get an "Unexpected token export" error.

**Comment by NicolasPetton** [comment]
kiemdoder <notifications@github.com> writes:

> When I try to evaluate something like
> ```
> export function add(a, b){ return a + b }
> ```
> with `M-x indium-eval-region` I get an "Unexpected token export"
> error.

That's expected, since you're evaluating the JS code outside of a
module. I think you will get the same behavior with Chrome/Firefox.

**Comment by NicolasPetton** [comment]
However if you omit the `export`, it should work.
