### ISSUE TITLE
Indium server error: Unexpected token . in JSON at position 281

### ISSUE THREAD

**Issue by dukereg** [NicolasPetton/Indium#217]
When I try to launch indium inside emacs I get an error: `Indium server error: Unexpected token . in JSON at position 281`.

I enabled `debug-on-error` and `indium-client-debug` before running `indium-launch` but it all seems fine on the client side. `*indium-debug-log*` only says:
```
Sent: ((id . 1) (type . configurations) (payload (action . list) (directory . /home/dukereg/dev/exercises/js/)))

Received: ((id . 1) (type . error) (payload (error . Unexpected token . in JSON at position 281)))
```

The config file was cobbled together from examples at the "Getting up and running" page (which clearly includes an unquoted IP address).
`/home/dukereg/dev/exercises/js/.indium.json`:
```
{
  "configurations": [
    {
      "name": "Web project local",
      "type": "chrome",
      "host": "localhost",
      "url": "http://localhost/myproject/index.html",
      "port": 9222
    }
    ,
    {
      "name": "Web project",
      "type": "chrome",
      "host": 192.168.22.1,
      "url": "http://192.168.22.1/myproject/index.html",
      "port": 9222
    }
    ,
    {
      "name": "NodeJS project",
      "type": "node",
      "command": "node ./blah.js",
      "inspect-brk": false
      "host": "localhost",
      "port": 9229
    }
  ]
}
```

I checked and, as expected from the error message, the problem was in the IP address for the "host" property in the second configuration object.

Position 281 corresponds to the "8" in the IP address `192.168.22.1`. My guess is that something is trying to parse it as a decimal value, but I have no evidence of that. 

I was not asked to select a configuration to choose between my two chromium and one nodejs configurations. I have no idea what server it is "sending" the config to in order to get back this error.

If I reorder the lines in the file, the position follows that digit in the IP address.

If I quote the IP address, in defiance of the examples given, I get a different error about unexpected quotes.

My emacs version is `GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-04-13`.
My indium client version is `20190715.1457`.
My OS is Arch Linux.
My chromium version is `Chromium 75.0.3770.142 Arch Linux`.
My node version is `v11.15.0`.

**Comment by NicolasPetton** [comment]
Thank you for the detailed report! I won't have time to debug this until next week,but I'll get back to you as soon as I can!

**Comment by NicolasPetton** [comment]
I could reproduce the issue ,and I just tried with the host in double quotes and that fixed the issue.

I pushed a fix in the documentation, but if you still get an error, please reopen this issue.
