### ISSUE TITLE
could not find executable (indium)

### ISSUE THREAD

**Issue by JohnConner** [NicolasPetton/Indium#218]
fresh Ubuntu 18 install, installed latest emacs from source installed indium from melpa.

sudo npm install -g indium

all seemed to go ok, but when tried indium-launch the status bar indicated that emacs could not find the binary for indium.
I manually added the path to the indium binary in my .profile, and the problem was resolved.

**Comment by NicolasPetton** [comment]
Have you setup nodejs properly? Do other bin files end up in your PATH?

**Comment by JohnConner** [comment]
node works fine, no problem. Like I said - after I added the location of the indium binary to my path, it worked fine. I have another machine that Indium worked without a problem. No clue what the difference was.

**Comment by NicolasPetton** [comment]
Ok, I'm closing the issue then.
