### ISSUE TITLE
building indium locally

### ISSUE THREAD

**Issue by baerrach** [NicolasPetton/Indium#222]
My emacs-fu has recently increased so I thought I'd try to contribute to Indium to get my node/jest issues sorted.

However, I have not progressed to the level of building emacs packages.

I've tried running `make`  but I get the error `Cannot open load file: No such file or directory, buttercup`

```
$ make
TRAVIS=true emacs -Q --batch -L . --eval "(require 'package)" --eval "(add-to-list 'package-archives '(\"melpa-stable\" . \"http://stable.melpa.org/packages/\"))" --funcall package-initialize \
-l buttercup \
-l test/test-helper.el \
-f buttercup-run-discover
Cannot open load file: No such file or directory, buttercup
make: *** [Makefile:38: test-elisp] Error 127
```

Buttercup being the BDD test framework isn't part of Indium.

Are there any documents on building Indium locally?

**Comment by baerrach** [comment]
Its been a lifetime ago that I used Makefiles.

Instead of just running `make` and praying I had a peek inside.

Running `make dependencies` installed what I needed.

Then `make` works fine.

Now to work out why I have `18 failures` from a clean clone.

**Comment by NicolasPetton** [comment]
`make dependencies` was what you were looking for. It's not documented, as I'd users to install Indium through Melpa. 

I'm closing this issue, but do you still have 18 failures?

**Comment by baerrach** [comment]
**40 specs, 0 failures**

However, I've just transitioned to `straight.el` so my Indium instance is hackable inside `~/.emacs.d/straight/repos/Indium` via git.

Running `make dependencies` is installing stuff into `~/.emacs.d/elpa/<package>` which is no longer being used since `straight.el` disables `package.el`.

I'll have to ponder that one...
