### ISSUE TITLE
Coffeescript inlined source maps in ephemeral javascript support

### ISSUE THREAD

**Issue by sandinmyjoints** [NicolasPetton/Indium#228]
We have a node application with an entrypoint in Javascript that calls `require('coffee-script/register')` in order to support some files in the application written in Coffeescript. The effect this has is to compile the Coffeescript to Javascript on the fly -- no Javascript files are written to disk, the compiled Javascript only exists in memory in the node process. Inline source maps are included in this ephemeral Javascript, however. 

When I add or remove breakpoints using Indium in those Coffeescript files, they don't work as expected. I manually compiled a Coffeescript file to a Javascript file, and when I noted the line and column position of a function I wanted to set a breakpoint on in the Javascript file, and navigated to that position within the Coffeescript file and set a breakpoint there (even though in the Coffeescript, it was something else entirely), it worked. It's like Indium isn't seeing the compiled Javascript, which maybe is what's going on. I'm wondering if there is any way for it to do so? Can it somehow get it from node via the debugging protocol?

**Comment by sandinmyjoints** [comment]
I guess one thing I can test is whether I can set breakpoints using Chrome as the debugger. My recollection is that I have done this in the past, but that would have been a while ago so I'm not 100% sure about it.

**Comment by NicolasPetton** [comment]
Yes, if you can set breakpoints in Chrome, then Indium should support it.

**Comment by NicolasPetton** [comment]
@sandinmyjoints Can you confirm that breakpoints work in Chrome?

**Comment by sandinmyjoints** [comment]
I haven't had the chance to do so. I'm with closing this issue for now since I don't know when I'll get a chance to move it forward.
