### ISSUE TITLE
The "locals" view only show a part of objects without telling its incomplete

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/Indium#23]
When displaying the locals (`l`), I see

```
session: Object { settings: Object, redirectToPeriod: function, getPeriod: function, setPeriod: function, onPeriodChange: function }
```

But session contains other keys beyond these. I would like to get a `...` at the end to show more keys are present but can't be displayed.

**Comment by NicolasPetton** [comment]
I know about this, but unfortunately, that's Chrome's object preview, and you will have the same issue in Chrome's DevTools:

![screenshot from 2017-04-10 11-31-43](https://cloud.githubusercontent.com/assets/123539/24855296/6f03f19a-1de1-11e7-8fdc-c2b9e9f99a1d.png)

I'll keep it open anyway, as it would be worth fixing.

**Comment by chris-kahn** [comment]
Is it not possible to expand object references at the moment either? This is pretty valuable I think, usually when I'm looking at the locals inspector in VS Code I want to dive deeper into an object, and it's a bit annoying to do this via the repl buffer.

**Comment by NicolasPetton** [comment]
It definitely is possible from the inspector buffer and the debugger locals, I wonder what you are referring to.

**Comment by chris-kahn** [comment]
I see it now, usually I'm using emacs in a terminal and it's not very obvious that they are clickable (no underlining). The keyboard shortcut `RET` seems to work in my windowed emacs but not terminal.

**Comment by DamienCassou** [comment]
Why did you close this one? Is it fixed?

**Comment by NicolasPetton** [comment]
It was marked as postponed for a long time, and as I said:
> I know about this, but unfortunately, that's Chrome's object preview, and you will have the same issue in Chrome's DevTools

So there's nothing I can do about it that I know of.
