### ISSUE TITLE
Import statement outside a module

### ISSUE THREAD

**Issue by dupuchba** [NicolasPetton/Indium#230]
Hello all,

First of all I'd like to thank Nicolas & contributors for this mode, I avoid really hard to write javascript but this mode make it a lot less painful. 

I have a question about the workflow.
Typically when I write clojure/elisp I have a REPL centric approach which is magic.
I'd like to replicate to the max this approach but I don't see how :
- when I load a buffer I got the `import statement outside a module`
- even if I could load the entire file, there are so much transformation between the source file and the dist that I really don't know how it could work

Thanks all for your time

**Comment by NicolasPetton** [comment]
Baptiste DUPUCH <notifications@github.com> writes:

> Hello all,

Hi!

Could you show us the code you're trying to evaluate?

Thanks,
Nico

**Comment by dupuchba** [comment]
for e.g.

```
import Vue from 'vue';
import Router from 'vue-router';
import Home from './views/Home.vue';

Vue.use(Router);

const router = new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'home',
      component: Home,
    },
  ],
});
```

**Comment by NicolasPetton** [comment]
I see. Can you try evaluating the import in Chrome's console, and tell
us if that works? If it works in Chrome, then it should work in Indium,
otherwise it should be considered a bug.

**Comment by dupuchba** [comment]
It does not work in chrome dev tool.
It is a Vuejs typical project.
I am wondering if it is even possible :'(

**Comment by dupuchba** [comment]
Before closing this issue, have you ever make it work ? importing module from console/indium ?
If so, is there a blank project that I can look at ?

**Comment by NicolasPetton** [comment]
TBH I never tried that.

**Comment by dupuchba** [comment]
Thanks a lot for your time and excellent mode ! 
I found a "trick" that match my need when working with Vuejs / Webpack project.

If you find a way to access Vue global object you can then call all the API and have a REPL workflow for checking/mutating state while testing your function !
In the Vuejs, when plugin is installed, you have the global object bind to $vm0
