### ISSUE TITLE
No completion in javascript buffer.

### ISSUE THREAD

**Issue by enesaki** [NicolasPetton/Indium#233]
Hello,

There is very good complétion in REPL buffer and in indium-scratch buffer.
In indium-scratch buffer or in REPL, company-mode display a liste after
typing .(dot) :

var testA = [];
testA.length
        constructor
        concat
        copyWithin
        .....

But no completion after .(dot) in  javascript buffer with
indium-interaction-mode : 
(this is the default completion of emacs/company) :

var testA = [];

testA.async
        await
      ...

Completion is not related to the variable.
Thanks for your help

*json-process-client-process* buffer
Indium server listening on 13840

This log append in REPL but nothing in indium-interaction-mode
*indium-debug-log*
Sent: ((id . 11) (type . runtime) (payload (action . getCompletion) (expression . this) (frameId)))

Received: ((id . 11) (type . success) (payload . [Object Function Array Number parseFloat parseInt Infinity NaN undefined Boolean String Symbol Date Promise RegExp Error EvalError RangeError ReferenceError SyntaxError TypeError URIError globalThis JSON Math console Intl ArrayBuffer Uint8Array Int8Array Uint16Array Int16Array Uint32Array Int32Array Float32Array Float64Array Uint8ClampedArray BigUint64Array BigInt64Array DataView Map BigInt Set WeakMap WeakSet Proxy Reflect decodeURI decodeURIComponent encodeURI encodeURIComponent escape unescape eval isFinite isNaN ByteLengthQueuingStrategy CountQueuingStrategy webkitRTCPeerConnection webkitMediaStream WebSocket WebGLVertexArrayObject WebGLUniformLocation WebGLTransformFeedback WebGLTexture WebGLSync WebGLShaderPrecisionFormat WebGLShader WebGLSampler WebGLRenderingContext WebGLRenderbuffer WebGLQuery WebGLProgram WebGLFramebuffer WebGLContextEvent WebGLBuffer WebGLActiveInfo WebGL2RenderingContext WaveShaperNode TextEncoderStream TextEncoder TextDecoderStream TextDecoder SyncManager SubtleCrypto StorageEvent Storage StereoPannerNode SourceBufferList SourceBuffer ScriptProcessorNode ScreenOrientation RTCTrackEvent RTCStatsReport RTCSessionDescription RTCRtpTransceiver RTCRtpSender RTCRtpReceiver RTCPeerConnectionIceEvent RTCPeerConnectionIceErrorEvent RTCPeerConnection RTCIceCandidate RTCErrorEvent RTCError RTCDataChannelEvent RTCDataChannel RTCDTMFToneChangeEvent RTCDTMFSender RTCCertificate Plugin PluginArray PhotoCapabilities PeriodicWave Path2D PannerNode OverconstrainedError OscillatorNode OfflineAudioContext OfflineAudioCompletionEvent NetworkInformation MimeType MimeTypeArray MediaStreamTrackEvent MediaStreamTrack MediaStreamEvent MediaStream MediaStreamAudioSourceNode MediaStreamAudioDestinationNode MediaSettingsRange MediaRecorder MediaEncryptedEvent MediaElementAudioSourceNode MediaCapabilities InputDeviceInfo ImageCapture ImageBitmapRenderingContext IIRFilterNode IDBVersionChangeEvent IDBTransaction IDBRequest IDBOpenDBRequest IDBObjectStore IDBKeyRange IDBIndex IDBFactory IDBDatabase IDBCursorWithValue IDBCursor GamepadHapticActuator GamepadEvent Gamepad GamepadButton GainNode EventSource DynamicsCompressorNode DelayNode DOMError CryptoKey Crypto ConvolverNode ConstantSourceNode CloseEvent ChannelSplitterNode ChannelMergerNode CanvasRenderingContext2D CanvasPattern CanvasGradient CanvasCaptureMediaStreamTrack BroadcastChannel BlobEvent BiquadFilterNode BeforeInstallPromptEvent BatteryManager BaseAudioContext AudioWorkletNode AudioScheduledSourceNode AudioProcessingEvent AudioParamMap AudioParam AudioNode AudioListener AudioDestinationNode AudioContext AudioBufferSourceNode AudioBuffer AnalyserNode postMessage blur focus close XPathResult XPathExpression XPathEvaluator XMLSerializer XMLHttpRequestUpload XMLHttpRequestEventTarget XMLHttpRequest XMLDocument WritableStream Worker Window WheelEvent VisualViewport ValidityState VTTCue URLSearchParams URL UIEvent TreeWalker TransitionEvent TransformStream TrackEvent TouchList TouchEvent Touch TimeRanges TextTrackList TextTrackCueList TextTrackCue TextTrack TextMetrics TextEvent Text TaskAttributionTiming StyleSheetList StyleSheet StylePropertyMapReadOnly StylePropertyMap StaticRange ShadowRoot Selection SecurityPolicyViolationEvent Screen SVGViewElement SVGUseElement SVGUnitTypes SVGTransformList SVGTransform SVGTitleElement SVGTextPositioningElement SVGTextPathElement SVGTextElement SVGTextContentElement SVGTSpanElement SVGSymbolElement SVGSwitchElement SVGStyleElement SVGStringList SVGStopElement SVGSetElement SVGScriptElement SVGSVGElement SVGRectElement SVGRect SVGRadialGradientElement SVGPreserveAspectRatio SVGPolylineElement SVGPolygonElement SVGPointList SVGPoint SVGPatternElement SVGPathElement SVGNumberList SVGNumber SVGMetadataElement SVGMatrix SVGMaskElement SVGMarkerElement SVGMPathElement SVGLinearGradientElement SVGLineElement SVGLengthList SVGLength SVGImageElement SVGGraphicsElement SVGGradientElement SVGGeometryElement SVGGElement SVGForeignObjectElement SVGFilterElement SVGFETurbulenceElement SVGFETileElement SVGFESpotLightElement SVGFESpecularLightingElement SVGFEPointLightElement SVGFEOffsetElement SVGFEMorphologyElement SVGFEMergeNodeElement SVGFEMergeElement SVGFEImageElement SVGFEGaussianBlurElement SVGFEFuncRElement SVGFEFuncGElement SVGFEFuncBElement SVGFEFuncAElement SVGFEFloodElement SVGFEDropShadowElement SVGFEDistantLightElement SVGFEDisplacementMapElement SVGFEDiffuseLightingElement SVGFEConvolveMatrixElement SVGFECompositeElement SVGFEComponentTransferElement SVGFEColorMatrixElement SVGFEBlendElement SVGEllipseElement SVGElement SVGDiscardElement SVGDescElement SVGDefsElement SVGComponentTransferFunctionElement SVGClipPathElement SVGCircleElement SVGAnimationElement SVGAnimatedTransformList SVGAnimatedString SVGAnimatedRect SVGAnimatedPreserveAspectRatio SVGAnimatedNumberList SVGAnimatedNumber SVGAnimatedLengthList SVGAnimatedLength SVGAnimatedInteger SVGAnimatedEnumeration SVGAnimatedBoolean SVGAnimatedAngle SVGAnimateTransformElement SVGAnimateMotionElement SVGAnimateElement SVGAngle SVGAElement Response ResizeObserverEntry ResizeObserver Request ReportingObserver ReadableStream Range RadioNodeList PromiseRejectionEvent ProgressEvent ProcessingInstruction PopStateEvent PointerEvent PerformanceTiming PerformanceServerTiming PerformanceResourceTiming PerformancePaintTiming PerformanceObserverEntryList PerformanceObserver PerformanceNavigationTiming PerformanceNavigation PerformanceMeasure PerformanceMark PerformanceLongTaskTiming PerformanceEventTiming PerformanceEntry Performance PageTransitionEvent NodeList NodeIterator NodeFilter Node Navigator NamedNodeMap MutationRecord MutationObserver MutationEvent MouseEvent MessagePort MessageEvent MessageChannel MediaQueryListEvent MediaQueryList MediaList MediaError Location KeyframeEffect KeyboardEvent IntersectionObserverEntry IntersectionObserver InputEvent InputDeviceCapabilities ImageData ImageBitmap IdleDeadline History Headers HashChangeEvent HTMLVideoElement HTMLUnknownElement HTMLUListElement HTMLTrackElement HTMLTitleElement HTMLTimeElement HTMLTextAreaElement HTMLTemplateElement HTMLTableSectionElement HTMLTableRowElement HTMLTableElement HTMLTableColElement HTMLTableCellElement HTMLTableCaptionElement HTMLStyleElement HTMLSpanElement HTMLSourceElement HTMLSlotElement HTMLShadowElement HTMLSelectElement HTMLScriptElement HTMLQuoteElement HTMLProgressElement HTMLPreElement HTMLPictureElement HTMLParamElement HTMLParagraphElement HTMLOutputElement HTMLOptionsCollection Option HTMLOptionElement HTMLOptGroupElement HTMLObjectElement HTMLOListElement HTMLModElement HTMLMeterElement HTMLMetaElement HTMLMenuElement HTMLMediaElement HTMLMarqueeElement HTMLMapElement HTMLLinkElement HTMLLegendElement HTMLLabelElement HTMLLIElement HTMLInputElement Image HTMLImageElement HTMLIFrameElement HTMLHtmlElement HTMLHeadingElement HTMLHeadElement HTMLHRElement HTMLFrameSetElement HTMLFrameElement HTMLFormElement HTMLFormControlsCollection HTMLFontElement HTMLFieldSetElement HTMLEmbedElement HTMLElement HTMLDocument HTMLDivElement HTMLDirectoryElement HTMLDialogElement HTMLDetailsElement HTMLDataListElement HTMLDataElement HTMLDListElement HTMLContentElement HTMLCollection HTMLCanvasElement HTMLButtonElement HTMLBodyElement HTMLBaseElement HTMLBRElement Audio HTMLAudioElement HTMLAreaElement HTMLAnchorElement HTMLAllCollection FormData FontFaceSetLoadEvent FontFace FocusEvent FileReader FileList File External EventTarget Event ErrorEvent Element DragEvent DocumentType DocumentFragment Document DataTransferItemList DataTransferItem DataTransfer DOMTokenList DOMStringMap DOMStringList DOMRectReadOnly DOMRectList DOMRect DOMQuad DOMPointReadOnly DOMPoint DOMParser DOMMatrixReadOnly DOMMatrix DOMImplementation DOMException CustomEvent CustomElementRegistry CompositionEvent Comment ClipboardEvent CharacterData CSSVariableReferenceValue CSSUnparsedValue CSSUnitValue CSSTranslate CSSTransformValue CSSTransformComponent CSSSupportsRule CSSStyleValue CSSStyleSheet CSSStyleRule CSSStyleDeclaration CSSSkewY CSSSkewX CSSSkew CSSScale CSSRuleList CSSRule CSSRotate CSSPositionValue CSSPerspective CSSPageRule CSSNumericValue CSSNumericArray CSSNamespaceRule CSSMediaRule CSSMatrixComponent CSSMathValue CSSMathSum CSSMathProduct CSSMathNegate CSSMathMin CSSMathMax CSSMathInvert CSSKeywordValue CSSKeyframesRule CSSKeyframeRule CSSImportRule CSSImageValue CSSGroupingRule CSSFontFaceRule CSS CSSConditionRule CDATASection Blob BeforeUnloadEvent BarProp Attr AnimationEvent AnimationEffect Animation AbortSignal AbortController WebKitCSSMatrix WebKitMutationObserver webkitURL parent opener top length frames closed location self window document name customElements history locationbar menubar personalbar scrollbars statusbar toolbar status frameElement navigator origin external screen innerWidth innerHeight scrollX pageXOffset scrollY pageYOffset visualViewport screenX screenY outerWidth outerHeight devicePixelRatio clientInformation event offscreenBuffering screenLeft screenTop defaultStatus defaultstatus styleMedia onanimationend onanimationiteration onanimationstart onsearch ontransitionend onwebkitanimationend onwebkitanimationiteration onwebkitanimationstart onwebkittransitionend isSecureContext onabort onblur oncancel oncanplay oncanplaythrough onchange onclick onclose oncontextmenu oncuechange ondblclick ondrag ondragend ondragenter ondragleave ondragover ondragstart ondrop ondurationchange onemptied onended onerror onfocus oninput oninvalid onkeydown onkeypress onkeyup onload onloadeddata onloadedmetadata onloadstart onmousedown onmouseenter onmouseleave onmousemove onmouseout onmouseover onmouseup onmousewheel onpause onplay onplaying onprogress onratechange onreset onresize onscroll onseeked onseeking onselect onstalled onsubmit onsuspend ontimeupdate ontoggle onvolumechange onwaiting onwheel onauxclick ongotpointercapture onlostpointercapture onpointerdown onpointermove onpointerup onpointercancel onpointerover onpointerout onpointerenter onpointerleave onselectstart onselectionchange onafterprint onbeforeprint onbeforeunload onhashchange onlanguagechange onmessage onmessageerror onoffline ononline onpagehide onpageshow onpopstate onrejectionhandled onstorage onunhandledrejection onunload performance stop open alert confirm prompt print queueMicrotask requestAnimationFrame cancelAnimationFrame captureEvents releaseEvents requestIdleCallback cancelIdleCallback getComputedStyle matchMedia moveTo moveBy resizeTo resizeBy scroll scrollTo scrollBy getSelection find webkitRequestAnimationFrame webkitCancelAnimationFrame fetch btoa atob setTimeout clearTimeout setInterval clearInterval createImageBitmap onappinstalled onbeforeinstallprompt crypto indexedDB webkitStorageInfo sessionStorage localStorage SharedArrayBuffer Atomics chrome WebAssembly LayoutShift PerformanceElementTiming ElementInternals FormDataEvent LargestContentfulPaint SharedWorker ReadableStreamDefaultReader WritableStreamDefaultWriter OffscreenCanvas UserActivation XSLTProcessor onformdata onpointerrawupdate ClipboardItem BackgroundFetchManager BackgroundFetchRecord BackgroundFetchRegistration MediaMetadata MediaSession MediaSource Notification PaymentInstruments PaymentManager PaymentRequestUpdateEvent Permissions PermissionStatus EnterPictureInPictureEvent PictureInPictureWindow PushManager PushSubscription PushSubscriptionOptions RTCDtlsTransport RTCSctpTransport RemotePlayback webkitSpeechGrammar webkitSpeechGrammarList webkitSpeechRecognition webkitSpeechRecognitionError webkitSpeechRecognitionEvent SpeechSynthesisErrorEvent SpeechSynthesisEvent SpeechSynthesisUtterance OffscreenCanvasRenderingContext2D speechSynthesis webkitRequestFileSystem webkitResolveLocalFileSystemURL openDatabase applicationCache Worklet ApplicationCache ApplicationCacheErrorEvent caches ondevicemotion ondeviceorientation ondeviceorientationabsolute AbsoluteOrientationSensor Accelerometer AudioWorklet Cache CacheStorage Clipboard Credential CredentialsContainer DeviceMotionEvent DeviceMotionEventAcceleration DeviceMotionEventRotationRate DeviceOrientationEvent FederatedCredential Gyroscope Keyboard KeyboardLayoutMap LinearAccelerationSensor Lock LockManager MediaDeviceInfo MediaDevices MediaKeyMessageEvent MediaKeys MediaKeySession MediaKeyStatusMap MediaKeySystemAccess MIDIAccess MIDIConnectionEvent MIDIInput MIDIInputMap MIDIMessageEvent MIDIOutput MIDIOutputMap MIDIPort NavigationPreloadManager OrientationSensor PasswordCredential RelativeOrientationSensor RTCIceTransport Sensor SensorErrorEvent ServiceWorker ServiceWorkerContainer ServiceWorkerRegistration StorageManager PaymentMethodChangeEvent PaymentAddress PaymentRequest PaymentResponse Presentation PresentationAvailability PresentationConnection PresentationConnectionAvailableEvent PresentationConnectionCloseEvent PresentationConnectionList PresentationReceiver PresentationRequest AuthenticatorAssertionResponse AuthenticatorAttestationResponse AuthenticatorResponse PublicKeyCredential USB USBAlternateInterface USBConfiguration USBConnectionEvent USBDevice USBEndpoint USBInterface USBInTransferResult USBIsochronousInTransferPacket USBIsochronousInTransferResult USBIsochronousOutTransferPacket USBIsochronousOutTransferResult USBOutTransferResult settings_js_version locale sprintf locale_data locale_simple l_dry l_dir l_lang ltd l ln lp lnp ld ldn ldp ldnp Handlebars html5 Modernizr $ jQuery EventEmitter2 decodeURIComponentSafe relativeDate tinycolor polyline Gettext DDG SM2_DEFER d w cd dz da fk fb fs fm fe fl fo fa fn fq fz ie io ir is ga gd rc rd rs rsd rdc rsc rtc rii rin rir rl rp reb rebc sx sy tl tlz tac tr ts tn tsl tz nir kurl is_mobile dow iosx slo ncku nckd ncf ncg nis nkda nkua nke nko nkt nkd nkn nkm nksb nks nkdc nkdm nkdt nkds nkf mousewheelevt nkw nrv nro nrs sendCount nrj nrc nrg nrl nrrel nrb nrm appendAdClass nrn nsr nul nutp nua nug nun iframeOpen openBlankWindow getLinkType adOrOrganicClick organicClick adClick iadt iad3 iad2 iad ieof fmy fmx daia daiq dam il irl rpc is_retina viewport_width viewport_height is_mobile_device k0 k1 k2 k3 k4 k5 k6 k7 k8 k9 ka kaa kb kab kc kac kd kad ke kae kf kaf kg kag kh kah ki kai kj kaj kk kak kl kal km kam kn kan ko kao kp kap kq kaq kr kar ks kas kt kat ku kau kv kav kw kaw kx kax ky kay kz kaz k10 k11 k12 k13 k14 k15 k16 k17 k18 k19 k20 k21 objectKey a autocompleteCallback TEMPORARY PERSISTENT constructor addEventListener removeEventListener dispatchEvent __defineGetter__ __defineSetter__ hasOwnProperty __lookupGetter__ __lookupSetter__ isPrototypeOf propertyIsEnumerable toString valueOf toLocaleString]))

Sent: ((id . 12) (type . runtime) (payload (action . getCompletion) (expression . a) (frameId)))

Received: ((id . 12) (type . success) (payload . [length constructor concat copyWithin fill find findIndex lastIndexOf pop push reverse shift unshift slice sort splice includes indexOf join keys entries values forEach filter flat flatMap map every some reduce reduceRight toLocaleString toString __defineGetter__ __defineSetter__ hasOwnProperty __lookupGetter__ __lookupSetter__ isPrototypeOf propertyIsEnumerable valueOf]))

-------------------------------------------------

**Comment by NicolasPetton** [comment]
That's expected. Indium only offers completion in the REPL buffer.

**Comment by mihaiolteanu** [comment]
> That's expected. Indium only offers completion in the REPL buffer.

Why not in the buffer itself?
