### ISSUE TITLE
cannot eval a buffer more than once if there are any const definitions

### ISSUE THREAD

**Issue by chadhs** [NicolasPetton/Indium#235]
I can't figure out how to leverage indium with any code that contains a const once you eval the buffer a single time.  I had the idea of having the node command in the indium config be `nodemon index.js` but that yields an error telling me that is an invalid command.

is this just not possible; or is something obvious whooshing over my head.

thanks!

**Comment by NicolasPetton** [comment]
Indeed, I made changes in the .indium.json config file to handle such cases, but it's not in master yet.

See https://github.com/NicolasPetton/Indium/commit/2cf4cf485888ae0dcfa79012872d3c835ab62355

**Comment by NicolasPetton** [comment]
@chadhs Commit 7ce9497 fixes the issue, however the NodeJS configuration settings have changed as well: https://indium.readthedocs.io/en/latest/setup.html#nodejs-configuration-options

**Comment by chadhs** [comment]
@NicolasPetton awesome; thanks for getting back to me, i will give this a try  shortly.  :-)
