### ISSUE TITLE
Connection refused using Indium, works with Chrome

### ISSUE THREAD

**Issue by sandinmyjoints** [NicolasPetton/Indium#236]
I have this configuration:
```
{
  "configurations": [
    {
      "name": "jest components",
      "type": "node",
      "port": "9028",
      "program": "node",
      "inspect-brk": true,
      "args": "./node_modules/.bin/jest --runInBand --config=jest-components.config.js --color=no src/components/vocab-quiz/stores/vocab-quiz/actions/test.js"
    }
  ]
}
```
When I `indium-connect` to it, I get `Received: ((id . 2) (type . error) (payload (error . connect ECONNREFUSED 127.0.0.1:9028)))`

When I manually start it with `node --inspect-brk --inspect-port 9028 ./node_modules/.bin/jest --runInBand --config=jest-components.config.js --color=no src/components/vocab-quiz/stores/vocab-quiz/actions/test.js`, Chrome sees it and I can use its debugger. Any idea what could be going on?

**Comment by NicolasPetton** [comment]
You need to start the node process when starting indium, the best way to do that is to `M-x indium-launch`, instead of `indium-connect`.
