### ISSUE TITLE
Can't list breakpoints in Emacs 27

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/Indium#237]
`indium-list-breakpoints` calls `xref--show-xrefs` with a list of xrefs as argument. However, this private function takes a `fetcher` as argument, not a list of xrefs. The `fetcher` must be a function that returns xrefs (see `xref--show-xref-buffer`). This changed in http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=62349fe82ad42d7d2a7fb19e40860ee5d6ebd017.

**Comment by ldionmarcil** [comment]
Same issue on emacs 28.0.50.
```M-x indium-truncate-lines
Debugger entered--Lisp error: (cl-assertion-failed ((functionp fetcher) nil))
cl--assertion-failed((functionp fetcher))
xref--show-xref-buffer((#<xref-item xref-item-1565041d0ac0>) ((window . #<window 1 on buf.ts>) (display-action)))
xref--show-xrefs((#<xref-item xref-item-1565041d0ac0>) nil)
indium-list-breakpoints()
funcall-interactively(indium-list-breakpoints)
call-interactively(indium-list-breakpoints record nil)
command-execute(indium-list-breakpoints record)
```

**Comment by NicolasPetton** [comment]
Fixed in master, closing.
