### ISSUE TITLE
Focus switches from emacs to chrome while debugging

### ISSUE THREAD

**Issue by nverno** [NicolasPetton/Indium#239]
I'm on Ubuntu with emacs 28. 

When stepping with the debugger attached to chrome, chrome steals focus after each step.  So, I have to switch back to emacs' window after each command.  Is this expected -- do you see the same behaviour?
Any guidance would be appreciated. Thanks!

**Comment by NicolasPetton** [comment]
nverno <notifications@github.com> writes:

Hi,

> When stepping with the debugger attached to chrome, chrome steals focus after each step.  So, I have to switch back to emacs' window after each command.  Is this expected -- do you see the same behaviour?
> Any guidance would be appreciated. Thanks!

Yes, Chrome will steal the focus if the devtools are open in Chrome. It
should not steal the focus otherwise though.

**Comment by nverno** [comment]
Thanks! That makes sense -- I suppose any fix would depend on the windowing system, so perhaps just close this?

**Comment by NicolasPetton** [comment]
Yes, closing.
