### ISSUE TITLE
 ‘map-put’ is an obsolete macro (as of 27.1)

### ISSUE THREAD

**Issue by Eason0210** [NicolasPetton/Indium#245]
I got the below errors when open html file with javascript code.
In the JS RPEL mode, the delay was very high when i inputed code.

`../../home/my-emacs/site-lisp/extensions/Indium/indium-client.el: ‘map-put’ is an obsolete macro (as of 27.1); use map-put! or (setf (map-elt ...) ...) instead  `
`../../home/my-emacs/site-lisp/extensions/Indium/indium-breakpoint.el: ‘map-put’ is an obsolete macro (as of 27.1); use map-put! or (setf (map-elt ...) ...) instead`

OS: Windows 10
Emacs: 28.0.50

**Comment by NicolasPetton** [comment]
Merged in master, closing.
