### ISSUE TITLE
Indium chrome project does not start httpd

### ISSUE THREAD

**Issue by timotheosh** [NicolasPetton/Indium#247]
Indium-launch on a chrome project does not start an httpd server. 
### How to replicate:
Install Indium from melpa
Create a javascript project directory
Place a minimal Indium project json file in project directory as .indium.json. e.g.
```json
{
    "configurations": [
        {
            "name": "proj1",
            "type": "chrome",
            "url": "http://localhost/index.html"
        }
    ]
}
```
Open a js file in the project, and run `indium-launch`

Indium connects to the debugger, and the repl is open, no logs reporting errors. But alas, chrome gets connection refused. There is no server serving the project files.

**Comment by HarryHenryGebel** [comment]
Indium is not in charge of starting an httpd, that is the job of the user. The user could be using any of who knows how many servers running on the localhost or remotely, it's not realistic for indium to know how to start and configure whichever server the user wants to use (especially if it is not hosted on the same machine as emacs.) If you wish to fire up a local server when indium is launched, set up a keybinding that launches the server then calls indium-launch.

**Comment by timotheosh** [comment]
I am fine with this answer (it's what I have done to get around it), but the docs seemed unclear on this point to me. From https://indium.readthedocs.io/en/latest/setup.html#starting-indium
```
Launch: M-x indium-launch Start a JavaScript process (Chrome or NodeJS) as specified from the configurations in the .indium.json project file.
```
