### ISSUE TITLE
WS error: make client process failed: Connection refused

### ISSUE THREAD

**Issue by sunwukung** [NicolasPetton/Indium#25]
When trying to evaluate the following command (from [Getting up and Running](https://indium.readthedocs.io/en/latest/setup.html#nodejs)):

`M-x indium-connect-to-nodejs RET 127.0.0.1 RET PORT RET PATH`

 I get the following error:

`websocket-open: make client process failed: Connection refused, :name, websocket to ws://localhost:9229//c6face84-df0e-4af2-90b1-c3ce0b54b4fd, :buffer, nil, :host, localhost, :service, 9229, :nowait, nil`

This is on:

- Emacs 25.1
- MacOS 10.12.4 
- node 7.2.1 

any ideas what's happening? project looks great btw...want to get it working so I can convert my team from Atom...

**Comment by NicolasPetton** [comment]
@sunwukung can you show how you started the node process?

**Comment by NicolasPetton** [comment]
I just tried with node v7.2.1 installed through `nvm`, and using the following command-line arguments:

  node --inspect --debug-brk index.js

And I cannot reproduce the issue.

**Comment by sunwukung** [comment]
Ah - it works if I add `--debug-brk` - but not without

**Comment by NicolasPetton** [comment]
The issue is that your node process probably exited before you try to connect to it.

It you add `--debug-brk`, the process is suspended until you attach the Indium connection to it.
