### ISSUE TITLE
unable to get app to display in chromium browser

### ISSUE THREAD

**Issue by lpanda2** [NicolasPetton/Indium#250]
Hi I'm new to Javascript for Emacs. I did the following to get everything set up:

Installed Chromium >=v60
Emacs Version: 26.2

Installed `js2` from Melpa

Set up a project with the following directory structure:
```
  /Users/lpanda/projects/jsAppProjects/modern-javascript/chapter_2:
  total used in directory 24 available 9223372036853496629
  drwxr-xr-x   6 lpanda  staff  192 Aug  1 12:18 .
  drwxr-xr-x   4 lpanda  staff  128 Aug  1 12:01 ..
  -rw-r--r--   1 lpanda  staff  196 Aug  1 12:18 .indium.json
  -rw-r--r--   1 lpanda  staff  303 Aug  1 12:01 index.html
  drwx------  27 lpanda  staff  864 Aug  1 12:18 nil
  -rw-r--r--   1 lpanda  staff   94 Aug  1 12:01 sandbox.js
```
FWIW the `nil` folder didn't exist until I ran the indium start code. Not really sure if it's supposed to be there...

My `.indium.json` file looks like:
```
{
  "configurations": [
    {
      "name": "Web project",
      "type": "chrome",
      "host": "0.0.0.0",
        "url": "http://0.0.0.0:3000/modern-javascript/chapter_2/index.html"
    }
  ]
}
```

When I try `M-x indium-launch` in the `.indium.json` file, a Chromium browser opens at the URL listed but nothing in the index.html appears. It says ERR CONNECTION REFUSED.

Can anyone help me out? I'm sorry if this isn't the right place to message about this. I thought I followed the instructions but I'm afraid I'm at a roadblock now. Thank you so much in advance!

**Comment by HarryHenryGebel** [comment]
Do you have a server running on port 3000? Indium doesn't startup the server to serve the webpage you are debugging, you have to provide that yourself (or use a server running on the web somewhere). Port 3000 sounds like it may be supposed to be started by 'npm start', I know create-react-app configures the app to run server on that port by default when 'npm start' is run.

**Comment by HarryHenryGebel** [comment]
As a side comment, don't go to 0.0.0.0 . It may often be functionally equivalent to 127.0.0.1 but it isn't the same thing. Use localhost or 127.0.0.1 . But I doubt that is the cause of your problem, I suspect you just don't have a server running on port 3000.

**Comment by HarryHenryGebel** [comment]
Essentially, indium accessing two addresses, the remote debugging service running in Chrome and the web server providing the page. The debugging server must use Chrome debugging protocol (which I think is only used by Chrome and Chromium) I think this would normally almost always be running on localhost on port 9222. The web server just has to be any normal HTTP server, and can be running on localhost or anywhere on the network that is accessible from your computer; Chrome can inspect any page, not just pages on your computer.

The `host` and `port` options specify where to find the Chrome remote debugging service, and the URL is whatever you would normally type into the address bar to get to the web page; if you aren't running a server the protocol to access a file on the hard drive through chrome is `file://full/path/to/file`. (I haven't tried to debug a file on the hard drive, but I assume it would work.)

I never specify host or port in by indium.json, unless you have an unusual setup the defaults (localhost and 9222) will always work, those options are only if Chrome is running on a different computer or at least IP address for some reason or if it can't bind 9222.

**Comment by HarryHenryGebel** [comment]
Note that I'm just an Indium user, I don't develop it. But that mental model of how Indium works has allowed me to use it successfully.

**Comment by lpanda2** [comment]
> It may often be functionally equivalent to 127.0.0.1 but it isn't the same thing. (For example, I believe it doesn't work on Windows.)

Thank you! Good to know.

> Do you have a server running on port 3000? Indium doesn't startup the server to serve the webpage you are debugging, you have to provide that yourself (or use a server running on the web somewhere).

This must be the reason. I just assumed Indium started the server. :) Is there a way to do that at all with Indium or do I need to go into the command line, do you know?

> Note that I'm just an Indium user, I don't develop it. But that mental model of how Indium works has allowed me to use it successfully.

Honestly, your mental model helped a lot, so thank you.
