### ISSUE TITLE
Eval error on fresh install for MacOs caused by json-process-client `Symbol's value as variable is void`

### ISSUE THREAD

**Issue by vitorqb** [NicolasPetton/Indium#255]
Hi!

Today I just installed indium on a fresh emacs installation on MacOs and when trying to `(require 'indium)` it gave me the following error:

```
Eval error ***  Symbol’s value as variable is void: json-process-client--application-create
```

After a little of debugging I found that for some reason the byte-compiled version of the `json-process-client` library was throwing this error, but the non compiled version works just fine. So I `rm json-process-client.elc`, keeping only the `.el` file, and it works just fine.

I was wondering (a) if that's not happening to anyone else and (b) if you know what could be causing this issue (if it's a library bug or something to do with MacOs).

Versions:
GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101)) of 2020-08-27
macOS Catalina 10.15.7
indium 20200116.1247
json-process-client 20190827.1858

PS: I would have opened a bug for `json-process-client` but I can't seem to access it's gitlab repository at https://gitlab.petton.fr/nico/json-process-client

**Comment by adityaathalye** [comment]
I'm seeing this on a fresh install on Ubuntu as well. 
- nvm version v8.17.0
- indium version 20201103.2040
- stock configuration in `.indium.json`
```json
{
    "configurations": [
        {
            "name": "Gulp",
            "type": "node",
            "program": "node",
            "args": "./node_modules/gulp/bin/gulp.js",
            "inspect-brk": true
        }
    ]
}
```

**Comment by NicolasPetton** [comment]
@DamienCassou any idea what's going on?

**Comment by DamienCassou** [comment]
I don't know, sorry.

**Comment by NicolasPetton** [comment]
I just tried with a fresh vanilla Emacs 27.1, installing Indium from MELPA, and I cannot reproduce the issue.

**Comment by jacksonbenete** [comment]
```
GNU Emacs 27.1 (compiled on Ubuntu 20.04.1 LTS)
node v15.7.0
npm 7.5.1
chromium 88.0.4324.96 snap
indium 2.1.7
```
I'm having this same error both trying with node and chromium.
But I prefer not to delete anything from my Emacs for now...

**Comment by SL-RU** [comment]
I've got the same issue

**Comment by bergmannf** [comment]
I also have the same problem (installing `indium` in doom-emacs).

For me what fixed the problem was adding `(require 'cl-lib)` to the top of the `json-process-client.el` file and recompiling.

@DamienCassou Maybe this is the fix, but I only have a very shallow elisp knowledge.

**Comment by DamienCassou** [comment]
What you suggest seems reasonable @bergmannf. I sent a PR for this https://gitea.petton.fr/nico/json-process-client/pulls/1. Thank you!

@NicolasPetton I don't have write access to https://gitea.petton.fr/nico/json-process-client. Can you please merge the PR?

**Comment by bergmannf** [comment]
I just updated my packages when using doom and with version 1.0.0 of json-process-client I don't see the error anymore.

If someone else that maybe isn't using an emacs distribution is also not seeing it anymore I think this Issue can be closed.
