### ISSUE TITLE
Is it possible to use other Chromium-based browsers?

### ISSUE THREAD

**Issue by NickRaleigh** [NicolasPetton/Indium#259]
Hello,
I use Brave as my daily driver for web development. Is it possible to use it to debug with Indium instead of Chromium/Chrome?

**Comment by NicolasPetton** [comment]
@NickRaleigh I've never used Brave, but if you can start it with `--remote-debugging-port` or equivalent, it might work. Have you tried customizing `indium-chrome-executable`?

**Comment by NickRaleigh** [comment]
@NicolasPetton yes that did the trick! Using `(setq indium-chrome-executable "brave")` will launch Brave instead of Chrome/Chromium. Thank you!

And a note for others who run into this issue as well, Ubuntu/Debian distros tend to use the executable name `brave-browser` as the executable name, and other distros just use the name `brave`.

**Comment by NicolasPetton** [comment]
Awesome! @NickRaleigh I'm glad that it just works.

**Comment by bnsv** [comment]
Mine is google-chrome instead of chrome,
so its 
`(setq indium-chrome-executable "google-chrome")`.
