### ISSUE TITLE
 Edits JavaScript source live. 

### ISSUE THREAD

**Issue by TatriX** [NicolasPetton/Indium#26]
It would be awesome to have an ability to live reload the code.
Which can be implemented using https://chromedevtools.github.io/debugger-protocol-viewer/1-2/Debugger/#method-setScriptSource

**Comment by NicolasPetton** [comment]
This is now work in progress, see the #set-script-source branch.

**Comment by TatriX** [comment]
http://tatrix.org/public/video/emacs/indium.ogv

**Comment by NicolasPetton** [comment]
The `set-script-source` branch has landed in master!
It's now in the `0.5.0` release, and documented here: https://indium.readthedocs.io/en/latest/code-evaluation.html#live-code-update-hot-swapping-javascript-sources
