### ISSUE TITLE
No idea why Chromium is waiting for Emacs

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/Indium#30]
Sometimes, Chromium waits for Emacs and Emacs shows a debugger at a particular line but there is no clue why. Maybe it's an invisible breakpoint, maybe it's an error in the code. Would it be possible to be more explicit?

**Comment by NicolasPetton** [comment]
- What do you mean by "Chromium waits for Emacs"?
- What debugger do you see (a JS debugger, edebug, something else?)
- Do you get errors in the *Messages* buffer?

**Comment by NicolasPetton** [comment]
Also have you checked the REPL for error messages after you proceed?
If you hit a debugger, it's probably because you have errors in your code :)
