### ISSUE TITLE
Emacs sometimes freezes while opening a connection

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/Indium#32]
It already happened a few times that Emacs freezes for around 10 seconds consuming 100% CPU after I politely asked `M-x indium-connect-to-chrome`. After the delay, the REPL gets refreshed and everything is back to normal.

**Comment by DamienCassou** [comment]
This just happened now while Chromium stopped at a breakpoint.

**Comment by NicolasPetton** [comment]
Do you have a recipe to reproduce it systematically?
