### ISSUE TITLE
Emacs stopping without a reason

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/Indium#36]
Sometimes Emacs stops on a line. The websocket buffer says it's because of a breakpoint but I killed all breakpoints (with `C-c b k`) and I don't see any anymore.

**Comment by NicolasPetton** [comment]
Is commit 72e8e44 fixing your issue?

**Comment by NicolasPetton** [comment]
@DamienCassou up?

**Comment by DamienCassou** [comment]
I'm closing for now and will reopen if the problem persists.

**Comment by DamienCassou** [comment]
Thanks for your hard-work.
