### ISSUE TITLE
Indium keybindings affect other modes like Org-mode

### ISSUE THREAD

**Issue by stardiviner** [NicolasPetton/Indium#40]
```elisp
(use-package indium
  :ensure t
  :init
  (dolist (hook '(js-mode-hook
                  js2-mode-hook
                  js3-mode-hook
                  ))
    (add-hook hook #'indium-interaction-mode))
  :config
  (setq indium-chrome-executable "google-chrome-unstable")
  )
```

I enabled Indium like upper. And found that `[C-x C-e]` is bind to `indium-eval-last-node`.

**Comment by NicolasPetton** [comment]
`C-x C-e` is also bound to `eval-last-sexp` in emacs-lisp-mode, is that an issue?

**Comment by stardiviner** [comment]
No, I mean why I only enable `indium-interaction-mode` in js modes, but it setup keybinding org-mode too?

**Comment by NicolasPetton** [comment]
It should not, and I cannot reproduce the issue. Are you sure `indium-interaction-mode` is not enabled in your org buffers?

**Comment by stardiviner** [comment]
After I restart Emacs, this issue disappeared. Sorry for distribution.

**Comment by NicolasPetton** [comment]
no problem! Thanks for reporting issues :)
