### ISSUE TITLE
While in debugger, I can't see the value of objects

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/Indium#41]
1. Add a breakpoint
2. Make sure to hit it
3. The debugger prints a message in the echo area
4. Move the cursor to a expression and press `C-x C-e`
5. You won't see the result in the echo area as the debugger keeps printing there

**Comment by NicolasPetton** [comment]
@DamienCassou would waiting 2 seconds be a solution, or would you like to remove the timer that reprints the debugger keybindings all together?

**Comment by DamienCassou** [comment]
It would be better. What about waiting for the current message to disappear before displaying the debugger again? What about making `?` display the message?

**Comment by NicolasPetton** [comment]
The message gets redisplayed already after commands, so I could just remove the timer.
