### ISSUE TITLE
is there a mailing list to ask questions?

### ISSUE THREAD

**Issue by haroldcarr** [NicolasPetton/Indium#42]
I'm having problems setting breakpoints.

**Comment by TatriX** [comment]
https://gitter.im/indium-emacs/Lobby

**Comment by NicolasPetton** [comment]
There's no mailing-list, but as @TatriX mentioned, there's a gitter root.

**Comment by NicolasPetton** [comment]
@haroldcarr you can also explain the issue you're facing here.
