### ISSUE TITLE
Preview booleans are always rendered as false

### ISSUE THREAD

**Issue by spacebat** [NicolasPetton/Indium#51]
If I enter `[{"one": true}]` into the JS repl, then inspect the resulting array, the buffer starts with:
```
Array[1]

  0: Object { one: false }
```
If I enter `[true]` then the result is printed with preview as:
```
Array[1] [ false ]
```
In both cases, inspecting the value itself renders the boolean correctly. I have tracked this to `indium-webkit--description` where the case for true is never matched. If I change the case matched for to the string "true" then both cases reported above are correct.

Incidentally I tried entering `{"key":true}` at the repl to test that directly rather than embedding it in an array, but got:
```
SyntaxError: Unexpected token : {  }
```

**Comment by NicolasPetton** [comment]
Fixed in 244a55d1a85ef013d7fbf0dc5cb28ec253989528
