### ISSUE TITLE
Not able to get up and running

### ISSUE THREAD

**Issue by dwrz** [NicolasPetton/Indium#57]
I tried following the documentation to get Indium running, but get stuck here:

"Start a process with M-x indium-run-node."

That command doesn't seem to exist.

Any ideas?

**Comment by TatriX** [comment]
Can you run `C-h f indium-connect-to-nodejs`?

**Comment by dwrz** [comment]
That doesn't seem to work. The only thing that comes up on swiper is indium-interaction-mode. Am I doing anything wrong?

**Comment by NicolasPetton** [comment]
@dwrz can you tell us which version of Indium have you installed, and how? Also, how did you load it?

**Comment by dwrz** [comment]
Thanks @NicolasPetton!

I installed it via MELPA, the current version is 20170519.1411. I'm on Emacs 25.2.

**Comment by babinc** [comment]
I had the same thing happen. I tried all kinds off stuff. I finally got the node command to come back. Below are things I tried

Closing all running node processes
Uninstalled and installed indium again
Double checked for errors in my emacs config

**Comment by NicolasPetton** [comment]
@dwrz do you require Indium? `(require 'indium)` in your Emacs config?

**Comment by NicolasPetton** [comment]
@dwrz What happens after you do `M-: (require 'indium) RET`?

**Comment by NicolasPetton** [comment]
@dwrz I found the problem: Indium-interaction.el only has an autoload for `indium-interaction-mode`. I'm removing it for now (I'll add autoloads later).

**Comment by NicolasPetton** [comment]
@dwrz can you tell me if 3316f78 fixes your issue?

**Comment by dwrz** [comment]
@NicolasPetton -- yes, and sorry, I ran `M-: (require 'indium) RET` and it worked. I didn't have it in my init and now the commands are showing up. I think I have another issue, but I'll search and open a new thread for it if I can't resolve it. Thanks very much!
