### ISSUE TITLE
Process indium-nodejs-process exited abnormally with code 9 node: bad option: --inspect

### ISSUE THREAD

**Issue by dwrz** [NicolasPetton/Indium#59]
I get the following when running indium-run-node:

    Process indium-nodejs-process exited abnormally with code 9
    node: bad option: --inspect

Running node from the terminal with `node --inspect --debug-brk` seems to work.

**Comment by NicolasPetton** [comment]
which version of nodejs do you have?

**Comment by dwrz** [comment]
7.10 -- I followed the documentation.

`/home/user/.nvm/versions/node/v7.10.0/bin/node`

**Comment by TatriX** [comment]
Could you please evaluate in emacs
```lisp
(locate-file "node" exec-path)
```
and in your shell
```sh
which node
```

**Comment by dwrz** [comment]
`/usr/bin/node`

**Comment by TatriX** [comment]
I think this is a reason. You should check https://github.com/purcell/exec-path-from-shell

**Comment by sudarshang** [comment]
Does indium support [nvm](https://github.com/rejeep/nvm.el)? That could be another option to get the right version of node.js to work with Indium.

**Comment by NicolasPetton** [comment]
@sudarshang @dwrz what puzzles me is that Indium starts the `node` process through bash, exactly for this.

@dwrz what does the following return `(shell-command-to-string "bash -c 'which node'")`

**Comment by TatriX** [comment]
As I can see it should be shell from `shell-file-name`, not bash.

**Comment by NicolasPetton** [comment]
@TatriX I see now that the exec path is anyway not setup correctly. I'll add a dependency to `exec-path-from-shell` which solves the problem on *nix.

**Comment by NicolasPetton** [comment]
@dwrz can you confirm that af23fc4 fixes the issue for you?

**Comment by dwrz** [comment]
@NicolasPetton -- confirming -- thanks for your time and help!
