### ISSUE TITLE
Sourcemap support

### ISSUE THREAD

**Issue by TatriX** [NicolasPetton/Indium#6]
Hi. Please take a look at https://github.com/TatriX/kite-mini.el
I've added some basic sourcemap support for similiar to jade kite-mini project.
It's actually very primitive but I hope you can find it usefull because currently most of the projects use some kind of transformers like babel or typescript.

So to make it work I'm using the following:

``` lisp
(defun kite-mini-update-custom ()
  (interactive)
  (let ((default-directory "~/my-projects/"))
    (shell-command "npm run build" "*kite-mini-compilation*"))
  (kite-mini-call-rpc
   "Debugger.setScriptSource"
   (let ((script (--find (string-suffix-p "my-project/dist/application.js" (plist-get it :url))
                         kite-mini-rpc-scripts)))
     (plist-put script :source-map (cons 'lazy-source-map "~/www/my-project/dist/application.js.map"))
     (list :scriptId (plist-get script :id)
           :scriptSource (kite-mini--get-string-from-file "~/www/my-project/dist/application.js")))
   (lambda (result)
     (kite-mini-send-eval
      "window.dispatchEvent(new CustomEvent('change', {detail: {filename: 'application.js'}}))"
      (lambda (result) (message "Kite update done"))))))
```

Then in the buffer with `kite-mini-mode` I can use `C-c C-k` to compile the project and update it on the fly and still get sourcemaps, so I can see actual code lines in the repl buffer.

**Comment by NicolasPetton** [comment]
Hi!

That looks interesting, would you consider putting this in the form of a
pull request?  I'd be happy to give you pointers and help if you need.

**Comment by TatriX** [comment]
Sure I'll try to make a pull request.

**Comment by NicolasPetton** [comment]
Indium 0.7.x now has support for sourcemaps, so I'm closing this ticket.
