### ISSUE TITLE
Indium should propose existing workspaces when it can't find one

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/Indium#65]
Sometimes I do `M-x indium-connect-to-chrome` from a directory outside of the JS project. This is annoying because the debugger won't find my local files. It would be great if `indium-connect-to-chrome` could ask for a known workspace to bind to if it can't find any where `indium-connect-to-chrome` is started. That could for example be implemented with a `defcustom` remembering workspaces.

**Comment by DamienCassou** [comment]
it would be even better if Indium could automatically populate known workspaces in the variable.

**Comment by TatriX** [comment]
You can `M-x cd [RET] /path/to/project` from the REPL buffer to fix the running connection.

**Comment by NicolasPetton** [comment]
@TatriX now you can do it, see 2389c05
