### ISSUE TITLE
Is OS Windows not supported?

### ISSUE THREAD

**Issue by Eoksni** [NicolasPetton/Indium#68]
I experience a lot of weird behavior on Windows - can't even press RET in the repl buffer. So should I make a detailed bug report or Windows is simply not supported so I shouldn't bother?

**Comment by NicolasPetton** [comment]
I have not tried Indium in Windows, but I see no reason why it should
not be supported.

Please create an issue with a more detail explanation of the problem.

**Comment by Eoksni** [comment]
Sure, here you go https://github.com/NicolasPetton/Indium/issues/69
