### ISSUE TITLE
indium repl doesn't work

### ISSUE THREAD

**Issue by Eoksni** [NicolasPetton/Indium#69]
Running `M-x indium-run-node RET node `  results in
```
exec-path-from-shell-printf: Non-zero exit code from shell E:/eoksni-dir/portable/emacs/emacs-25.2-x86_64/libexec/emacs/25.2/x86_64-w64-mingw32/cmdproxy.exe invoked with args ("-l" "-i" "-c" "c:/Program Files (x86)/Gow/bin/printf.exe ’__RESULT\\000%s\\000%s\\000__RESULT’ \"${PATH-3ee3c256aae424afd6f79e5709ff36c2}\" \"${MANPATH-3ee3c256aae424afd6f79e5709ff36c2}\"").  Output was:
"’c:/Program’ is not recognized as an internal or external command,
operable program or batch file.
```
The function to drop this error was `indium--setup-exec-path` and it seems to be optional (by the way, to me it seems like a terrible idea to manipulate global exec-path without warning or interacting with user in any way - if I understand correctly what this function does) so I executed `(setq indium-exec-path-setup t)` by myself to skip this function, then node process is started fine and I am even given the repl buffer:
![image](https://user-images.githubusercontent.com/2010503/26980437-62790cee-4d5c-11e7-8d4b-863878101c90.png)
But when I press RET, nothing happens. I looked up that RET is bound to `indium-repl-return`, so I M-x'ed it with same result - nothing happens at all, no errors in `*Messages*`.

I don't know if it is relevant, but I start `indium-run-node` with this file:
```js
/**
 * adsfasdfasdfasfd
 * @param {*asdfasf} input 
 */
function qwer(input) {
    const aaa = "asdf";
    let bbb = "vcvzx";
    for (let i = 0; i < aaa.length; ++i) {
        let mmm = 10;
        let bbb = 111111;
    }
}
qwer()
```

By the way, I also tried `M-x indium-scratch RET 5+5 C-x C-e` also with no success, just nothing happens without any error messages.

Win 10, emacs 25.2.1, started it with `emacs -Q`, installed indium like so:
```elisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
```
`M-x package-refresh-contents`
`M-x package-install RET indium`

**Comment by NicolasPetton** [comment]
Thanks for reporting the issue!

I'd need a few more info:

1. which version of NodeJS are you running?
2. how did you install NodeJS?
3. in `eshell`, which version of nodejs do you have?

**Comment by NicolasPetton** [comment]
Regarding `exec-path-from-shell`, I will most probably remove it and document the problem in the manual instead.

**Comment by Eoksni** [comment]
both in eshell and cmd:
```
> node --version
v7.7.1
```
I installed it by downloading install package from their web site https://nodejs.org/en/ from the "Current" button. It was a while ago, so now they have different version on the main page - 8.1.0.

**Comment by NicolasPetton** [comment]
Ok, and what's the content of the `*node process*` buffer?

**Comment by Eoksni** [comment]
`*node process*`:
```
Debugger listening on port 9229.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/78493de5-2651-409b-b771-a608fac96148
```

**Comment by NicolasPetton** [comment]
Ok, thanks. Nothing wrong from what I see, I'll need to fire up a Windows VM and try it.

**Comment by NicolasPetton** [comment]
@Eoksni could you try with a connection to a Chrome tab in Windows?

**Comment by Eoksni** [comment]
@NicolasPetton yep, with Chrome the repl works fine.

**Comment by Eoksni** [comment]
Btw I used `indium-connect-to-chrome`, not an `indium-run-chrome` as chrome is not in my PATH.

**Comment by NicolasPetton** [comment]
Thank you, this is helpful.

**Comment by Eoksni** [comment]
No problem! Thank you for the very quick replies, looking forward to using indium after this issue is fixed - indium looks very nice, at least from the gifs at the readme ;)

**Comment by NicolasPetton** [comment]
Commit e9b0104 works for me with node 8.1.0 in Windows 10. You should get a message similar to the following in the `*node process*` buffer:

```
Debugger attached
```

If you see 

```
Waiting for the debugger to disconnect...
```

It means that the node process has exited, that might be why you cannot execute anything in the REPL.

**Comment by Eoksni** [comment]
Ok I will try tomorrow with 8.1.0. Btw I don't see any of those messages with 7.7.1, just `Debugger listening on port 9229.`

**Comment by Eoksni** [comment]
It does work with 8.1.0, awesome! Thank for your help.

P. S. Still no `Debugger attached` in the `*node process*` tho:
```
Debugger listening on ws://127.0.0.1:9229/0f0a2058-f5b7-41fc-8762-ce7103ea96b5
For help see https://nodejs.org/en/docs/inspector
(node:17700) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
```
