### ISSUE TITLE
Infinite Loop Protection

### ISSUE THREAD

**Issue by dwrz** [NicolasPetton/Indium#70]
I accidentally evaluated the buffer in indium-scratch, which had an infinite loop as written. The REPL was stuck printing returned values. 

After quitting indium -- not sure if this was the right course of action -- I saw a bunch of errors scrolling through the minibuffer, too quickly to read.

Then Emacs froze.

Again, not sure if there is a better command to run, or if this is really a node.js issue, but it would be nice if there were some way to stop evaluation of the loop.

**Comment by NicolasPetton** [comment]
David Wen Riccardi-Zhu <notifications@github.com> writes:

> I accidentally evaluated the buffer in indium-scratch, which had an
> infinite loop as written. The REPL was stuck printing returned
> values.

Can you show me some code snippet? 

> After quitting indium -- not sure if this was the right course of
> action -- I saw a bunch of errors scrolling through the minibuffer,
> too quickly to read.
>
> Then Emacs froze.

I will try to reproduce it.

**Comment by dwrz** [comment]
How about this:
`while (1 > 0) { console.log('Infinity!'); }`

Emacs didn't freeze this time, but it basically becomes unusable -- M-x, C-x C-b, etc. -- not working.

**Comment by NicolasPetton** [comment]
David Wen Riccardi-Zhu <notifications@github.com> writes:

> How about this:
> `while (1 > 0) { console.log('Infinity!'); }`

What happens in Chrome devtools?

**Comment by dwrz** [comment]
Surprisingly, it crashes the browser there, too.

repl.it has a nice feature: https://repl.it/Ir4p/0.

A few other browser based REPL's I've come across also seem to have it.

Nicolas Petton <notifications@github.com> writes:

> David Wen Riccardi-Zhu <notifications@github.com> writes:
>
>> How about this:
>> `while (1 > 0) { console.log('Infinity!'); }`
>
> What happens in Chrome devtools?
>
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/NicolasPetton/Indium/issues/70#issuecomment-309384028

-- 
dwrz|朱为文

**Comment by NicolasPetton** [comment]
Since Chrome doesn't protect you from infinite loops, I'm not sure Indium should. I'm keeping this issue open to collect opinions.

**Comment by dwrz** [comment]
Thank you, Nicolas. I'm quite new to JS development and Emacs, so am not sure what's best; I also realize the feature might not be trivial to implement. 

One difference I'd point out is that a crash in Emacs is more likely to affect work outside the project (personal org-mode buffers, irc, etc.). 

That said perhaps the real solution is that the user should code more carefully, employ more stringent auto-save, or start a separate Emacs session for dev work. : )

**Comment by NicolasPetton** [comment]
David Wen Riccardi-Zhu <notifications@github.com> writes:

> That said perhaps the real solution is that the user should code more
> carefully, employ more stringent auto-save, or start a separate Emacs
> session for dev work. : )

Well, the best would be to have support for it, but since V8 doesn't
provide anything like that, it will be quite tricky to implement in
Indium.

**Comment by NicolasPetton** [comment]
As I don't think it's easy doable to prevent infinite loops, I'm closing this issue.
