### ISSUE TITLE
test failure on Travis Linux: "No buffer named *JS REPL*"

### ISSUE THREAD

**Issue by dunn** [NicolasPetton/Indium#71]
I was trying to update a Homebrew formula for Indium, and when Travis runs `buttercup -l test/test-helper.el -L .` on a "Precise" Linux worker I see these test failures:
```
========================================
Repl output should display a prompt
error: (error "No buffer named *JS REPL*")
========================================
Repl output should display a welcome message
error: (error "No buffer named *JS REPL*")
========================================
Repl output should be able to clear all output
error: (error "No buffer named *JS REPL*")
========================================
Repl output should be able eval and print results
error: (error "No buffer named *JS REPL*")
========================================
Repl output should be able to inspect objects
error: (error "No buffer named *JS REPL*")
Ran 90 specs, 5 failed, in 28.7 seconds.
```
Full logs: https://travis-ci.org/dunn/homebrew-emacs/jobs/241658581#L1308

Node is installed, and the tests pass on the macOS worker.  Any idea what might be going on?  Thanks!

**Comment by NicolasPetton** [comment]
Alex Dunn <notifications@github.com> writes:

> I was trying to update a Homebrew formula for Indium, and when Travis
> runs `buttercup -l test/test-helper.el -L .` on a "Precise" Linux
> worker I see these test failures:

Does it work locally?

My guess is that it's a timeout issue. These tests start a node
process and do integration tests. The timeout for the node process to be
started it 1 second.

**Comment by NicolasPetton** [comment]
@dunn Have you tried to run the tests locally?

**Comment by dunn** [comment]
Hey, sorry for letting this linger.  The tests do pass locally, just not on Travis (I've seen this happen elsewhere).

Where should I try bumping the timeout?  I tried increasing the `sleep-for` calls in `test-helper.el` but that didn't work.

**Comment by NicolasPetton** [comment]
You should also increase the `sleep-for` calls in
`test/integration/indium-nodejs-integratoin-test.el` and in `indium-repl-integration-test.el`.

**Comment by dunn** [comment]
Checking now, but there are some `void-function` errors in the way: https://gist.github.com/anonymous/1b7a0d741991eb372d12d160e728091d

Should `test-helper.el` just `(require 'indium)` to avoid each test file having to require things separately?

**Comment by NicolasPetton** [comment]
Alex Dunn <notifications@github.com> writes:

> Checking now, but there are some `void-function` errors in the way:
> https://gist.github.com/anonymous/1b7a0d741991eb372d12d160e728091d

Can you try again? There was a dependency issue with sourcemap yesterday
that has been fixed.

**Comment by dunn** [comment]
Same thing: `(void-function indium-connection-nodejs-p)`.

**Comment by NicolasPetton** [comment]
That's weird, because the build is passing on my CI https://gitlab.petton.fr/nico/Indium/-/jobs/343
And it also works locally with `./run-tests.sh`.

Can you tell me how you are running the tests?

**Comment by NicolasPetton** [comment]
Also, have you run `cask install`?

``` bash
cask install
cask exec buttercup -l test/test-helper.el -L .
```

**Comment by NicolasPetton** [comment]
Travis builds are fine now, I'm closing this issue. If it's still a problem for you, feel free to reopen it.
