### ISSUE TITLE
Is JSX support planned ?

### ISSUE THREAD

**Issue by lepieru** [NicolasPetton/Indium#72]
I did not found the aswer on the web so I ask here: *is JSX support planned ?*

**Comment by NicolasPetton** [comment]
Since Indium supports sourcemaps, provided that you compile jsx sources with sourcemaps, you should be able to use Indium with it.

I'm not using jsx myself, but I'd like to know how it works for you if you give it a try.

**Comment by NicolasPetton** [comment]
I'm closing this issue for now. Feel free to reopen it or open a new one if you have more questions.
