### ISSUE TITLE
Add support for webkit browsers

### ISSUE THREAD

**Issue by NicolasPetton** [NicolasPetton/Indium#77]
The current webkit backend actually implement the Chrome protocol, which has diverged from Webkit when they forked it with Blink.

A new webkit backend would be needed, and the chrome/nodejs backend should be renamed to indium-v8.el

**Comment by jjrh** [comment]
Oh is this why i'm getting errors with map-elt when doing 'indium-connect-to-chrome' ?

`map-elt: Wrong number of arguments: (lambda (k l) (nthcdr 1 (assoc k l))), 3`

**Comment by NicolasPetton** [comment]
No, that would be a different bug :)

Chrome is not using webkit (it forked it).

Could you open a separate bug report, explaining how to reproduce the issue? Thanks!

**Comment by NicolasPetton** [comment]
As webkit's not using websockets anymore, getting Indium to work with it be much trickier. I'm closing this one for now.
