### ISSUE TITLE
Cannot get breakpoint location

### ISSUE THREAD

**Issue by crazyatnet** [NicolasPetton/Indium#78]
Cannot get breakpoint location

**Comment by NicolasPetton** [comment]
Hi! Thanks for reporting an issue!
Could you detail the issue you're facing?

**Comment by crazyatnet** [comment]
My config is spacemacs,windows 10 x64 system &  GNU Emacs 25.2.1 (x86_64-w64-mingw32)
 of 2017-04-24

**Comment by NicolasPetton** [comment]
@crazyatnet thanks.

To reproduce the issue, I'll need step by step instructions. Could you provide that?

**Comment by crazyatnet** [comment]
I start my emacs，open a express project and start server with M-x indium-run-node, node .,continue,"This requires closing the current connection and its process.  Are you sure? (y or n) y" ;when i edit a javascript file Enabled modes belows.When i add a breakpoint with C-c b b in the script,i get a error "Cannot get breakpoint location".Other my node is v8.2.1 on windows 10 x64.

Enabled minor modes: Ace-Pinyin Ace-Pinyin-Global Anzu Async-Bytecomp-Package
Auto-Composition Auto-Compression Auto-Encryption Auto-Highlight-Symbol
Bug-Reference-Prog Clean-Aindent Column-Number Company Cursor-Sensor
Diff-Auto-Refine Display-Time Electric-Indent Eval-Sexp-Fu-Flash Evil
Evil-Escape Evil-Local Evil-Search-Highlight-Persist Evil-Surround Eyebrowse
File-Name-Shadow Flx-Ido Flycheck Flycheck-Pos-Tip Font-Lock Git-Gutter+
Global-Anzu Global-Auto-Revert Global-Company Global-Eldoc
Global-Evil-Search-Highlight-Persist Global-Evil-Surround Global-Flycheck
Global-Font-Lock Global-Git-Commit Global-Git-Gutter+ Global-Hl-Line
Global-Linum Global-Page-Break-Lines Global-Pangu-Spacing
Global-Semantic-Idle-Scheduler Global-Semantic-Idle-Summary
Global-Semantic-Stickyfunc Global-Semanticdb Global-Spacemacs-Leader-Override
Global-Undo-Tree Global-Vi-Tilde-Fringe Goto-Address-Prog Helm Highlight-Numbers
Highlight-Parentheses Hl-Todo Holy Hs Ido-Vertical Indium-Interaction
Info-Breadcrumbs-In-Mode-Line Js2-Imenu-Extras Line-Number Linum Mouse-Wheel
Override-Global Pangu-Spacing Persp Popwin Projectile Rainbow-Delimiters Recentf
Save-Place Savehist Semantic Shell-Dirtrack Show-Smartparens
Show-Smartparens-Global Smartparens Spaceline-Helm Spaceline-Info
Spacemacs-Leader-Override Tern Transient-Mark Undo-Tree Vi-Tilde-Fringe
Volatile-Highlights Which-Key Winner Winum Xterm-Mouse Yas Yas-Global

**Comment by NicolasPetton** [comment]
If you are using indium with an express project, wouldn't you have to start node with `node ./bin/www`?

**Comment by crazyatnet** [comment]
Of course,I start server with "node ." after "M-x indium-run-node".

**Comment by NicolasPetton** [comment]
Is the express app working as expected when you start it with `indium-run-node`?

**Comment by crazyatnet** [comment]
Yes，server started and working properly.My project is like this [example](https://github.com/strongloop/loopback-getting-started).

**Comment by NicolasPetton** [comment]
Huy Le <notifications@github.com> writes:

> I confirm the same issue with `emacs -Q` and indium installed from
> melpla-stable with both browser and node. This won't happen if
> `indium-interaction-mode` is toggled prior to `indium-run-node` or
> `indium-connect-to-chrome`.

Can you please try installing Indium from MELPA (and not MELPA Stable)?

**Comment by crazyatnet** [comment]
My indium installed from MELPA and version is 20170728.1109.

**Comment by NicolasPetton** [comment]
@huylenq the problem is that the package on MELPA stable is **very** old, so please install it from MELPA.

@crazyatnet I'll try to reproduce it with your repo example.  Could you tell me in which file you tried to set a breakpoint? Thanks!

**Comment by huylenq** [comment]
@NicolasPetton sorry for late response, the same issue does happen with package installed from MELPA

**Comment by NicolasPetton** [comment]
@huylenq thanks, I'll investigate.

**Comment by crazyatnet** [comment]
@NicolasPetton In sever/server.js.

**Comment by NicolasPetton** [comment]
@crazyatnet @huylenq could you give it another try with the latest build from MELPA? A lot has changed in Indium WRT breakpoint handling, and the issue might have been fixed.

**Comment by jsjolen** [comment]
Hi!

I've successfully replicated this with version 20171204.128 from MELPA.
This is in an Electron project (after connecting to it with i-c-t-c).

I haven't made a small test for you to replicate the issue with, sorry.

I do know that breakpoints worked for me a couple of days ago.

**Comment by NicolasPetton** [comment]
Johan Sjölén <notifications@github.com> writes:

> I haven't made a small test for you to replicate the issue with,
> sorry.

A link to a repository and a short description to reproduce the issue
would be enough, do you think you could provide that?

**Comment by jsjolen** [comment]
Sorry @NicolasPetton, it's a proprietary repo :-(

**Comment by NicolasPetton** [comment]
Johan Sjölén <notifications@github.com> writes:

> Sorry @NicolasPetton, it's a proprietary repo :-(

Any other way I could reproduce it?

**Comment by NicolasPetton** [comment]
I still cannot reproduce the issue, so I'm closing it for now. If it's still a problem for you, fee free to reopen it (a recipe would be great).

**Comment by timur-han** [comment]
I also experience this issue by the way on my Windows machine...

**Comment by NicolasPetton** [comment]
@timur-han can you give me steps to reproduce it?

**Comment by jsjolen** [comment]
I used to have this issue but it disappeared spontaneously (as far as I can tell). Sorry @NicolasPetton :-/

**Comment by jsjolen** [comment]
Alright so the issue is specifically in source files which are not part of the main file as set by an Electron process.

**Comment by NicolasPetton** [comment]
ok, thanks. 

The best would be to give me simple steps to reproduce the issue, could you do that?

**Comment by jsjolen** [comment]
I'll give it a go to try and reproduce the issue with a small project. I'll msg again if I succeeded.

**Comment by jsjolen** [comment]
You can clone this repo for the files I used: https://github.com/jsjolen/indiumtest

What you need is:

1. A main file which has a script-ref in the main html file loaded by Electron (renderer process)

2. Another file (let's call it foo) which the main file requires.

Indium can't set breakpoints in foo because Electron gives no locations back but all of the input seems reasonable. It can however set breakpoints in the main file. I don't know if Indium can do anything about it because it seems like it's acting reasonably.

Here's some input info from my main project where I've stripped the paths:

**Succesful**

location = [cl-struct-indium-location 34 0 "index.js"]
file = "index.js"
url = "file:///index.js"

indium-backend-register-breakpoint(v8 [cl-struct-indium-breakpoint nil #<overlay from 1256 to 1291 in index.js> "index.js" [cl-struct-indium-location 34 0 "index.js"] ""])

**Unsuccesful**


location = [cl-struct-indium-location 39 0 "foo.js"]
file = "foo.js"
url = "file:///foo.js"
indium-backend-register-breakpoint(v8 [cl-struct-indium-breakpoint nil #<overlay from 1608 to 1632 in foo.js> "foo.js" [cl-struct-indium-location 39 0 "foo.js"] ""])
