### ISSUE TITLE
Download sourcemap file if it wasn't found on disk

### ISSUE THREAD

**Issue by TatriX** [NicolasPetton/Indium#81]
Sourcemaps and sources are often served from the web server dynamically.
For example a popular `create-react-app` tool uses `webpack-dev-server` to serve them.
Currently Indium expects that sourcemap file can be found on the disk which is not the case in the example above.

I think Indium should first check if there is a file on the disk and otherwise download it from the network.

Also it's worth mentioning that sourcemaps can be quite big, so downloading and parsing them synchronously can be quite time consuming. For example `bundle.map.js` from the `create-react-app` is `1.7M` in size.

**Comment by NicolasPetton** [comment]
This has been fixes in master.
