### ISSUE TITLE
error msg when running indium-run-node in emacs

### ISSUE THREAD

**Issue by zaxxoff** [NicolasPetton/Indium#84]
(node:22801) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.

And I get `Exception in websocket callback! (void-function seq-map-indexed)` on the bottom status bar

**Comment by NicolasPetton** [comment]
Thanks for reporting the issue!

1. the deprecation warning is ok, though we should ret rid of by using `--inspect-brk`
2. which version of Emacs are you using?
3. how did you install Indium?

**Comment by NicolasPetton** [comment]
@zaxxoff does `(require 'indium)` fix your problem?
