### ISSUE TITLE
Add hotkey to "Inspect expression" command

### ISSUE THREAD

**Issue by TatriX** [NicolasPetton/Indium#89]
It would be awesome if one could use `E` hotkey in the debugger mode to run a new inspect command.
Also adding `e` and `E` hotkeys to the `locals` and `stack` buffers can be a good thing too.

**Comment by NicolasPetton** [comment]
Agreed!

**Comment by NicolasPetton** [comment]
I'm unsure about the `locals` and `stack` buffers, so I'll leave this part out for now.

**Comment by NicolasPetton** [comment]
@TatriX I went with `C-u e` in the debugger.
