### ISSUE TITLE
100% CPU usage on Typescript + webkit + Angular2

### ISSUE THREAD

**Issue by Malabarba** [NicolasPetton/Indium#91]
## What I did

1. `ng serve` (ng is the ng-cli helper, which uses webpack under the hood).
2. `google-chrome --user-data-dir=/tmp --remote-debugging-port=9222 https://localhost:4200`.
3. `M-x connect-to-chrome` in Emacs.

## What happened

The REPL worked fine at first. Both for evaluation and completion. But as soon as I tried to edit some file, live reloading kicked in and Emacs popped to a buffer containing a single line describing some error. From there on Emacs because quite slow to respond (with keypresses taking about 1 sec to register). My system monitor indicated that the `emacs` process was taking 100% of one of the CPUs. That's when I killed Emacs and got back to work. :-)

Anyway, thanks for the package. I from the couple of minutes that I used it I can see it's pretty nice.

**Comment by NicolasPetton** [comment]
Thanks for the bug report.

The symptoms you describe remind me of a recent fix in Indium.  Can you tell me which version of Indium you're using?

**Comment by NicolasPetton** [comment]
> Emacs popped to a buffer containing a single line describing some error. 

Could you paste the error?

**Comment by jojojames** [comment]
Quick tangent, is indium supposed to work with Typescript?

**Comment by NicolasPetton** [comment]
In theory, yes, except for code evaluation with `C-x C-e`. In practice, sourcemap support is still young and doesn't work with Typescript yet.

**Comment by NicolasPetton** [comment]
@Malabarba could you try again with the latest revision of master? It might just work :tm: :)

**Comment by Malabarba** [comment]
It does! At least the REPL seems to work 100%, and the inspector is pretty awesome.

Anything that deals with source files is not so good, but I think that's to be expected. Thanks for this Nico!

**Comment by NicolasPetton** [comment]
Glad the REPL works fine!

Dealing with source files should work with a bit of work. 

@Malabarba Could you tell me how you set up your project? I've never used typescript or angular.

**Comment by jojojames** [comment]
@NicolasPetton I'm curious what you think would need to be done for Typescript debugging to work.

Would a sample Typescript project help? (Maybe in React or React Native)

**Comment by NicolasPetton** [comment]
> Would a sample Typescript project help? (Maybe in React or React
> Native)

Yes, it would definitely help.

**Comment by yzmism** [comment]
@NicolasPetton I created a React and React Native Typescript project. Hope this helps.

https://github.com/yzmism/ReactTypeScript
https://github.com/yzmism/ReactNativeTypeScript

**Comment by NicolasPetton** [comment]
"Hiep D. Nguyen" <notifications@github.com> writes:

> @NicolasPetton I created a React and React Native Typescript
> project. Hope this helps.

Thank you! I'll test them ASAP.

**Comment by yzmism** [comment]
@NicolasPetton No problem, let me know how it goes.
