### ISSUE TITLE
indium-connect-to-chrome throws error

### ISSUE THREAD

**Issue by jjrh** [NicolasPetton/Indium#93]
Fresh install of indium installed via melpa with no custom configuration. 

> GNU Emacs 25.2.50.1
> Version 61.0.3163.49 (Official Build) beta (64-bit)
> google-chrome-beta --remote-debugging-port=9222 --user-data-dir=debug_user_data

Running indium-connect-to-chrome

`Contacting host: 127.0.0.1:9222`
`map-elt: Wrong number of arguments: (lambda (k l) (nthcdr 1 (assoc k l))), 3`

I believe indium-chrome--connect-to-tab is the function that breaks. 

For fun I tried replacing map-elt with (cdr (assoc 'url tab)) and it was able to get the url value fine, but things obviously break later on. 

Hope this helps!

**Comment by NicolasPetton** [comment]
Thanks for reporting the issue!

I suspect something's wrong with map.el, but I can't be sure.
Could you paste here the result of:

```elisp
(map-elt '((a . 1) (b . 2)) 'b)
```

**Comment by jjrh** [comment]
Nicolas Petton writes:

> I suspect something's wrong with map.el, but I can't be sure.
> Could you paste here the result of:
>
> (map-elt '((a . 1) (b . 2)) 'b)

map-elt: Wrong number of arguments: (lambda (k l) (nthcdr 1 (assoc k l))), 3 [2 times]

**Comment by DamienCassou** [comment]
@jjrh can you please type `M-x find-function RET map-elt RET C-h v default-directory RET` and tell us what is in the console? It should be something like '/usr/local/share/emacs/25.2/lisp/emacs-lisp'.

**Comment by jjrh** [comment]
Damien Cassou writes:

> @jjrh can you please type M-x find-function RET map-elt RET C-h v
> default-directory RET and tell us what is in the console? It should be
> something like '/usr/local/share/emacs/25.2/lisp/emacs-lisp'.

default-directory is a variable defined in ‘C source code’.
Its value is "/usr/local/share/emacs/25.2.50/lisp/emacs-lisp/"
Local in buffer map.el.gz; global value is nil

**Comment by NicolasPetton** [comment]
@jjrh do you still have the same issue?

You're problem seems to be related to `map.el` not working properly with your setup.
Could you try the following recipe:

`$ emacs -Q`

Then evaluating in a scratch buffer:

```
(require 'map)
(map-elt '((a . 1) (b . 2)) 'b)
```

**Comment by NicolasPetton** [comment]
@jjrh I cannot reproduce this issue, so I'm closing the ticket. If it's still a problem for you, feel free to reopen it.
