### ISSUE TITLE
Reason for lack of autoloads?

### ISSUE THREAD

**Issue by blaenk** [NicolasPetton/Indium#98]
I'm curious why there seems to be a lack of autoloads? I'd prefer to load indium only when I run certain comments like `indium-run-node`. I could use use-package to define my own via `:commands` for example but given the lack of them in the package itself I was curious if there's a reason for that, maybe then it wouldn't be correct for me to add them on my end.

**Comment by NicolasPetton** [comment]
Jorge Israel Peña <notifications@github.com> writes:

> I'm curious why there seems to be a lack of autoloads? I'd prefer to
> load indium only when I run certain comments like `indium-run-node`. I
> could use use-package to define my own via `:commands` for example but
> given the lack of them in the package itself I was curious if there's
> a reason for that, maybe then it wouldn't be correct for me to add
> them on my end.

There's no reason, it's a long time overdue.

If you want to work on that, I'd gladly accept a pull request!
